### ISSUE TITLE
Support '~' in file paths

### ISSUE THREAD

**Issue by dcherian** [OceanParcels/parcels#1043]
`FieldSet.from_netcdf` does not support expanding `~` in the filenames. It would be very convenient if it could do so.

**Comment by erikvansebille** [comment]
Thanks for bringing this up, @dcherian. But since the [`glob` package](https://docs.python.org/3/library/glob.html) that we use in Parcels does not support expanding `~` either, this is not too trivial to implement and would require a big rewrite that would probably create a more messy code. So for now I think we won't support this, unless someone comes up with a clean solution

**Comment by dcherian** [comment]
The way to do it is `glob.glob(os.path.expanduser(input_pattern))` (I think)

**Comment by erikvansebille** [comment]
OK thanks; that seems easy enough. Don't you want to try putting this into the code yourself, so that you also get acknowledged as Parcels contributor? The line to change is https://github.com/OceanParcels/parcels/blob/master/parcels/fieldset.py#L276, I think. You can create a fork, test if it works and then do a Pull Request ?
