### ISSUE TITLE
What actually is an interpolation error?

### ISSUE THREAD

**Issue by nvogtvincent** [OceanParcels/parcels#1069]
I'm trying to debug a `Field interpolation error`/`InterpolationError` I am getting at apparently random locations and times with a SummedField. However, I am not sure what actually triggers this error as I can't find any documentation for this error and looking through the code, I can't work out what triggers it either. Common causes of errors when interpolating include querying out of bounds (but this would trigger a `OutOfBoundError`, NaNs in the dataset (but this cannot be the issue in this case since there are no NaNs in the data and in any case, particles are triggering the error in the middle of the ocean), or incorrectly setting up arrays (but this also cannot be the issue here since Parcels starts fine, `InterpolationError`s just get triggered at random points during execution). I believe that the code carrying out interpolations for JIT mode is `parcels.h` but I am not sure how parcels works out which error to trigger when interpolating.

Some insights into which conditions trigger this error would be very much appreciated!

**Edit:** I think I've found the relevant code in `index_search.h`, looks like it's something to do with parcels trying to interpolate a particle outside of the identified cell? Not sure why this would have been triggered but will do some more digging...

**Comment by erikvansebille** [comment]
Hi @nvogtvincent. I see that you found that these errors are typically thrown in `index_search.h` (at least, when you run with `JITParticle`). Indeed, these errors occur when for some reason, the particle is not located within the correct cell. 

In our experience, this only sometimes happens on a Curvilinear Grid and when cells are extremely skewed and/or rotated, such as near the Arctic in a tripolar (e.g. NEMO/ORCA) grid. Could that be the case in your simulation too?

**Comment by nvogtvincent** [comment]
Thanks for the reply @erikvansebille, these errors occured when using CMEMS reanalysis products which have been regridded to regular grids (1/12 deg for GLORYS12, 1/5 deg for WAVERYS) - so curvilinear yes, but not extremely skewed or rotated. Around 80% of particles seeded triggered this error within a year, at locations indicated by the red points below, so the distribution is quite random and doesn't seem to correspond to any particular problem spot on the grid:

![trajectories](https://user-images.githubusercontent.com/22178225/127313071-c2c48628-f7fa-4d52-90b5-1569f2ad7b0b.png)

Now that issue #1070 seems to be solved, I will try to do some more digging to work out which product exactly was triggering this error (GLORYS12, WAVERYS, or both).

**Comment by erikvansebille** [comment]
hmm, this is unexpected; I have never seen this large number of `InterpolationErrors` over such a wide area before. Please let me know what you find during the digging (and please be aware that I might respond slowly from tomorrow onward, because of summer holidays)

**Comment by nvogtvincent** [comment]
This problem has continued to baffle me. I thought I had figured out the problem (I thought it was related to my beaching Kernel) but alas it is now occurring in cases with the base JITParticle class alone. It seems that the issue occurs with a SummedField (I thought I had reproduced it even without a SummedField, but I may have been mistaken). 

I've put a very simple test-case [here](https://github.com/nvogtvincent/croco_scripts/blob/main/marine_debris_test/) where I've seeded one particle which generates this interpolation error. The velocity fields (in the MODEL_DATA dir) are surface velocity and surface stokes directly from the CMEMS reanalyses, so very standard datasets which have been used with parcels many times before. The interpolation error occurs near the equator (so it can't be due to some strange grid distortion). The best clue I've found is that the error often occurs at a latitude which is a multiple of 0.2, which is the grid resolution of the stokes field. But the issue doesn't seem to be the stokes field itself because the error doesn't occur when I _only_ use the stokes field.

**Comment by erikvansebille** [comment]
Thanks for this clean and concise test-case @nvogtvincent, I downloaded it and was able to replicate the bug. 

Upon very quick first inspection, I suspect that the bug is related to (due to?) the `WARNING: Flipping lat data from North-South to South-North` message. Indeed, the latitudes in the Ocean fields run from -6 to 2, but in the Wave fields they run from 2 to -6. While the Wave field is then flipped automatically by Parcels, this somehow gets messed up when the Grids are combined. 

I'll dig deeper, but could you also try to recreate the bug with wave fields that have latitude ordered from south to north? Why is this not the case in the first place, in your fields?

**Comment by erikvansebille** [comment]
OK, I've now created a fix to the InterPolation Errors themselves in @1072; turned out that the assessment if a particle fell outside of a grid cell was a bit too strict (up to numerical precision). With this fix, your minimal code now works for me

Note that the flipping of latitudes is still a bit 'dodgy' and may potentially lead to wrong sign of meridional velocity; so please tread very carefully if you see this warning come up. It's still a good idea to try fix your netcdf files and/or critically check if your particles move the way you expect them to move!

**Comment by nvogtvincent** [comment]
Thank you @erikvansebille - for pointing out my mistake with the latitude flipping (I had checked the current velocities for coherence with trajectories but not the stokes drift) and for hopefully solving this problem. I've flipped the latitudes in my stokes drift files and I'll check whether this fix solves the issue in the full simulations once the pull request is merged. Your explanation makes sense though so I expect it will work.

**Comment by erikvansebille** [comment]
Well, I think these are two different points: the _many_ InterpolationErrors you had probably come from the flipped latitudes in the Stokes fields; but there might still be very occasional InterpolationErrors that I fixed in #1072. So it would be good if you could confirm this hypothesis of mine by testing your simulations with the non-flipped Stokes drift in the current master first (and report if indeed that was the problem)

**Comment by nvogtvincent** [comment]
Oh sorry, I ran a test this morning with the corrected (non-flipped) Stokes drift fields and the first interpolation error occured at the exact same point as with the flipped Stokes drift fields (which is probably not surprising since the crash occured at a cell boundary which is the issue you described above). I did not add an exception for InterpolationErrors so it crashed when that first error occured. I'll rerun it to see if the many InterpolationErrors still occur.

**Comment by nvogtvincent** [comment]
Well this is slightly embarassing but it turns out that [this figure I shared earlier](https://github.com/OceanParcels/parcels/issues/1069#issuecomment-888227727) is not correct and only a very small number of particles were ever affected by this error (around 1 in 100,000) - which were probably those borderline cases that will hopefully be ironed out by that fix. FYI, the runs with the flipped and corrected stokes drift fields were identical, so it seems like parcels was able to cope sensibly with the flipped field (although I now recognise that it is good practice to rectify this beforehand and carry out these checks).

**Comment by erikvansebille** [comment]
Ah, good to know. I'll close this issue then
