### ISSUE TITLE
Documentation link still points to 2.2.1 version

### ISSUE THREAD

**Issue by albertotb** [OceanParcels/parcels#1118]
It seems that the documentation link https://oceanparcels.org/gh-pages/html/ still points to the documentation of the old version.

**Comment by erikvansebille** [comment]
Thanks for the message, @albertotb. However, the documentation _was_ updated after the release of v2.3.0 on 13 August 2021, see [this commit on the oceanparcles website repo](https://github.com/OceanParcels/oceanparcels_website/commit/f701ac22198e0fc5aa2a3f49d0f53da0f0a51e26#diff-eb07356d45580ed109d0fd4dccba03893bc70dd1a35d3d83d086023677ca665e).

I do understand your confusion about `rng` and `ParcelsRandom`. This is because of the line below which automatically renames the `rng` module to `ParcelsRandom`.
https://github.com/OceanParcels/parcels/blob/0df79e6cea94913e1b1565443e653fe72e87de62/parcels/__init__.py#L14 
 

Hope this clarifies?

**Comment by albertotb** [comment]
Thanks for the quick response. Yes, it does, but I'm still seing the old version string in the documentation. Maybe it is the correct one but the version string was not updated? Let me provide an screenshoot:

![image](https://user-images.githubusercontent.com/6514690/149117427-8988128c-237c-4314-b517-a04972c2e8d4.png)

Note the 2.2.1 in the top left corner.

**Comment by erikvansebille** [comment]
Ah, thanks for spotting! This version number has to be updated by hand (I can't find a way of linking it to a git tag on the sphinx documentation page), and we'd forgotten to do this for the last way releases. I'll update asap
