### ISSUE TITLE
Irregular ROMS grid

### ISSUE THREAD

**Issue by jwongala** [OceanParcels/parcels#1129]
Hello, I am using parcels and am wondering if it can use an irregular ROMS grid? Thank you for your assistance.

**Comment by erikvansebille** [comment]
What do you exactly mean with an irregular ROMS grid? A rotated grid? Because Parcels can work with that. See e.g. the [Schilling et al (2020) paper](https://doi.org/10.1111/fog.12473) and the code for these simulations at https://github.com/jaseeverett/TailorParticleTracking

Note, by the way, that there is some discussion about vertical velocities in ROMS and how to incorporate them in Parcels, see e.g. https://github.com/OceanParcels/parcels/issues/620, https://github.com/OceanParcels/parcels/issues/765 and https://github.com/OceanParcels/parcels/issues/759

**Comment by jwongala** [comment]
Thank you for the information. It uses a curvlinear grid. I think what I am looking for is CurvilinearSGrid in issue #620.

**Comment by jwongala** [comment]
Hello. I am working on getting a ROMS with a curvilinear irregular grid read into parcels, but I would like to nest this ROMS into another ROMS that has a rectilinear grid. Is this possible to do in parcels without regridding the curvilinear grid? Thank you for all of your assistance!

**Comment by erikvansebille** [comment]
Hi @jwongala. I don't think that this is possible at the moment. The way that nesting works in Parcels, I'd be surprised if it can deal with curvilinear grids that are nested in rectilinear grids. It will be a major effort to rewrite that code. So I'm afraid we can't really help you here..

**Comment by jwongala** [comment]
Mahalo @erikvansebille! Even if it is not possible, this is helpful to know. And now I know how I should move forward.
