### ISSUE TITLE
Suggestion for new example in the Diffusion tutorial

### ISSUE THREAD

**Issue by RomanIMMSP** [OceanParcels/parcels#1158]
Dear Parcels community

In many lagrangian simulations, the precalculated velocity fields are used. They allow simulating the transfer of lagrangian particles due to currents (advection). However, sometimes diffusion processes are also important. Using uniform diffusion coefficients Kh is the simplest way to solve this problem. But, in the case of complex currents, the coefficient of horizontal diffusion is not uniform - Kh(i,j). There are several methods allowing calculate Kh using values of velocities and lon-lat resolutions. One of the simplest ways is using the Smagorinsky method. 
I suppose to add a new example in the Diffusion tutorial by using horizontal diffusion calculated by the Smagorinsky method.
A short tutorial and a source code are given in the attached files. I think it could be useful for new Parcels users. The source code was created with the help of Daan Reijnders.

All the best,
Roman
[Smag_Diff_Tutorial_Draft.docx](https://github.com/OceanParcels/parcels/files/8389429/Smag_Diff_Tutorial_Draft.docx)
[example_smagdiff.txt](https://github.com/OceanParcels/parcels/files/8389434/example_smagdiff.txt)

**Comment by erikvansebille** [comment]
Thanks @RomanIMMSP, for this contribution! Really great that you built this. But in order to more efficiently incorporate this into Parcels, can I ask you to open a Pull Request with your suggested additions? See https://www.asmeurer.com/git-workflow/ for some tips on how to do that

The advantage of doing this via a PR are:
1. It will be easier for us to comment on the code and help improve it 
2. It will be easier to merge your code into the main branch
3. You will more explicitly get credited for the contribution

So can you please create a PR with your example_smagdiff as py file and your tutorial as ipynb file, both in the parcels/examples/ directory?

**Comment by RomanIMMSP** [comment]
Dear Erik

I am not sure that reply to this email will approach you.

In any case, thank you very much for your answer. I am a new user of the
Parcels model. Also I just joined GitHub, therefore everything is new for
me. But I will try to follow your recommendations to create a PR on Git
Workflow.

I must say that I have received several mentions about Parcels models as a
very powerful tool for Lagrangian modeling. Therefore I decided to start
working with it. Actually, I asked for assistance in Daan Reijnders. He
helps me very much for better understanding. I suppose that he is from your
scientific group.

Best wishes,
Roman


пт, 8 апр. 2022 г. в 13:30, Erik van Sebille ***@***.***>:
