### ISSUE TITLE
Update documentation for ParticleSet.from_particlefile 

### ISSUE THREAD

**Issue by claudiofgcardoso** [OceanParcels/parcels#1198]
Hello all,

The addition of zarr as an output format (#1165) is a great step forward, as it significantly improves the storage efficiency of my large particle files! It is also important to note that the initialisation of a ParticleSet from a .zarr particle file is also possible. So I suggest to update the parcels documentation for `ParticleSet.from_particlefile()` so that other users know that this functionality is also possible with zarr. 

Cláudio

**Comment by erikvansebille** [comment]
Hi @claudiofgcardoso, thanks for the comment. Yes, it would be a good addition to also support `zarr` in `ParticleSet.from_particlefile()`. But I'll do that as part of the larger refactoring project this summer, where I'm implementing dumping directly to `zarr` during a `pset.execute()` (instead of dumping to temporary npy files). 

There are at least three advantages of using `zarr` directly:
1. It doesn't require a conversion step at the end of the run anymore (and thus fixes issues like https://github.com/OceanParcels/parcels/issues/1193#issuecomment-1185440967). 
2. It will be much easier to inspect data when the execute is still running. 
3. It will hopefully also reduce file size of the output

See the branch at https://github.com/OceanParcels/parcels/tree/dump_to_zarr to check progress. It's still a bit too early for a Pull Request, but hopefully this is a complete feature by the end of August!

**Comment by claudiofgcardoso** [comment]
Hi @erikvansebille, glad to read that Parcels is migrating to `zarr` and I'm looking forward for this merge! There's no need to keep this issue open so I'll close it :)

**Comment by erikvansebille** [comment]
Thanks @claudiofgcardoso! FYI, the branch is now also a PR, see https://github.com/OceanParcels/parcels/pull/1199
