### ISSUE TITLE
Question about particle size

### ISSUE THREAD

**Issue by jwongala** [OceanParcels/parcels#1225]
Hello. I have a question about determining individual particle sizes similar to what was done in [Reint-Fisher et al., 2022](https://bg.copernicus.org/articles/19/2211/2022/#section8). The authors were able to "use 25 size bins within this range, releasing 4 identical particles per bin at each release location..." I was wondering if there was a tutorial on how to implement this. I went through their repo and was unsure of how to implement this. Mahalo for all of your assistance!

**Comment by reint-fischer** [comment]
Hi @jwongala , thanks for your interest! I am happy to point to the lines in our repo that define the particle size and answer any questions.

First we define our own [ParticleSet](https://github.com/OceanParcels/biofouling_3dtransport_2/blob/main/Simulation/kernels.py#L8) in [kernels.py](https://github.com/OceanParcels/biofouling_3dtransport_2/blob/main/Simulation/kernels.py), with a [Variable representing the radius of a particle](https://github.com/OceanParcels/biofouling_3dtransport_2/blob/main/Simulation/kernels.py#L50). We set the argument `to_write` to `'once'`, because the plastic radius doesn't change in our simulation.

```
class plastic_particle(JITParticle):
    r_pl = Variable('r_pl', dtype=np.float32, to_write='once')
```

Then, in [Simulation.py](https://github.com/OceanParcels/biofouling_3dtransport_2/blob/main/Simulation/Simulation.py), we [create an array of radii](https://github.com/OceanParcels/biofouling_3dtransport_2/blob/main/Simulation/Simulation.py#L299), for every released particle (location, number 1-4, size), using the function [`uniform_release`](https://github.com/OceanParcels/biofouling_3dtransport_2/blob/main/Simulation/utils.py#L22-L36) in [utils.py](https://github.com/OceanParcels/biofouling_3dtransport_2/blob/main/Simulation/utils.py). This function uses `np.repeat()` and `np.tile()` to create an array based on the number of sizeclasses, locations, and particles per location.

```
def uniform_release(n_locs, n_particles_per_bin, n_bins, e_max=-3, e_min=-5):
    '''
    Create a set of particle radii with a fixed amount of particles per bin for a given number of release locations.
    The bins are spaced logarithmically.
    :param n_locs: number of release locations
    :param n_particles_per_bin: number of particles per bin:
    :param n_bins: number of bins between 1E-e_max and 1E-e_min
    :param e_max: Exponent of the largest particle. -3 -> 1E-3 m = 1 mm
    :param e_min: Exponent of the smallest particle. -6 -> 1E-6 = 1 um
    '''
    sizes = np.logspace(e_min, e_max, n_bins)
    location_r_pls = np.repeat(sizes, n_particles_per_bin)
    r_pls = np.tile(location_r_pls, [n_locs, 1])
    return r_pls
```

```
r_pls = uniform_release(n_locs, n_particles_per_bin, n_sizebins)
```
Finally we [initialize the `ParticleSet`](https://github.com/OceanParcels/biofouling_3dtransport_2/blob/main/Simulation/Simulation.py#L301-L311) with the array of radii among other Variables.

```
 pset = ParticleSet.from_list(fieldset=fieldset,         # the fields on which the particles are advected
                                pclass=plastic_particle,            # the type of particles (JITParticle or ScipyParticle)
                                lon= lon_release,                       # a vector of release longitudes 
                                lat= lat_release, 
                                time = startdate,
                                depth = z_release,
                                r_pl = r_pls)
```

I hope that helps and am happy to answer any questions,

Reint

**Comment by erikvansebille** [comment]
Hi @jwongala, I hope that @reint-fischer's answer helped you. I'm closing this Issue now, let us know if you need further information
