### ISSUE TITLE
Automatically setting MPI when library is found.

### ISSUE THREAD

**Issue by axnsantana** [OceanParcels/parcels#1261]
Hi,

I have `mpi4py` and  `mpich` installed on my environment but as a requirement of another script, not Parcels. 
Thus, Parcels automatically loads the `MPI` package and consequently loads the `KMeans` from `sklearn.cluster`.
https://github.com/OceanParcels/parcels/blob/33f490210d1b1dabbf85bf45f86c06e4b4bfa411/parcels/collection/collectionsoa.py#L16-L25

So, even though I do not want to run parcels in parallel, I will need to install the scikit-learn.
In my specific case, it is a problem because one of the machines is not compatible with the recent versions of sklearn.

Could we change parcels to use a parameter or a variable from the environment to flag when using the MPI?

**Comment by axnsantana** [comment]
Hi @erikvansebille, thank you for the workaround it fixes the dependency on sklearn.

It will continue to set up the MPI environment without asking for it. But I have no details if that makes any difference. 
Maybe without executing the script with mpirun, the mpi4py will run as a single process.
I did the test and it ran, but I have no more details if that will use more resources for example.

When I said about parameter I was referring to a parameter in the creation or execution of the particle set, some like parallel=True.

**Comment by erikvansebille** [comment]
Hi @axnsantana, good to hear that the workaround works. Running with `MPI` nut only one processor should not lead to a slowdown in my experience.

A parameter for `useMPI=True` is quite tricky to implement at the moment, because of how collections and particle sets are initiated. I gave it a try but you quickly need to get very deep into the code; also because MPI is used in many different places. To be honest, I don't think it's worth the effort just for this single use-case. I propose we merge #1262 into master and that then solves it?

**Comment by axnsantana** [comment]
Yes, it solves it! I got your point about the parameter.
Thanks!
