### ISSUE TITLE
Explore switching to trajan package for plotting of Parcels output

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#1319]
The [trajan](https://github.com/OpenDrift/trajan) package is a great new way of visualising the output of Lagrangian trajectory data, including for Parcels. I know that a few people are using it already for their analysis of Parcels output.

As we make very clear at the top of the [output tutorial](https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_output.ipynb), Parcels does not include advanced analysis or plotting functionality, which users are suggested to write themselves to suit their research goals. 

The plotting routines that ship with Parcels were built to be able to show some plots/animations in the tutorial notebooks; not much more. 

Now, since the maintenance of the plotting routines in Parcels is quite cumbersome, I'd like to propose using trajan for the plotting in the notebooks. I propose this would then become Parcels v2.5.0.

@knutfrode and @gauteh, do you think that trajan is sufficiently developed for us to rely on it for the plotting in the tutorials? Anything we should be aware of as we start switching from our own plotting routines to trajan?

**Comment by knutfrode** [comment]
Hi Erik!
It is nice to hear that you are interested in cooperating on the TrajAn project.
The overall idea is quite simple: whereas it is good to have a variety of drift model since they have different approaches, strengths and weaknesses, the analysis and visualisation of the output is more of a technical issue, where we can all save efforts by making a joint generic and sound tool. Also this facilitates inter-model-comparisons, which tend to be very useful and enlightening.
For the case of OpenDrift, plotting and analysis methods have been bundled, but we have come to the conclusion that it is better to extract these as a separate package, revolving not around a specific model, but rather around a common data format: the netCDF CF-convention for trajectory data, which is used also by other models, and importantly: also for drifter observations.

So whereas the idea of TrajAn have matured over some time, it is only very recently (November) that we started the coding. After some initial testing, we are quite happy about the main structure, which we believe to be very flexible (largely thanks to building on Xarray).
However, there has not been much further development this year, and we plan to continue quite soon to settle some more things regarding the structure ("skeleton") before starting to add more functionality ("meat").
@gauteh and I hope to polish the structure within the next month or two, before continuing to add more functionality, and also then opening more up for others to contribute with adding their analysis methods of interest.
Also we will move it to a neutral GitHub repository, to stress that it is independent of any drift model.

So far it is basically only a minimalistic demonstration of the concept, with just a few simple plotting and analysis methods. And, as you have already seen, there has not been much focus on robustness yet - but this is of course an important design criteria. I will comment on that in https://github.com/OpenDrift/trajan/issues/47

Thus, you'd might also want to delay a little to base Parcels examples visualisation on TrajAn until it is more robust, and as there might be some minor changes in the API in the coming two months.

**Comment by erikvansebille** [comment]
OK, thanks for the explanation, @knutfrode. I fully subscribe to your analysis of the need for a robust, platform-independent, plotting package for Lagrangian trajectories. I'd be happy to help out with the development where I can! 

I'll keep an eye out for progress in the coming months, and will leave this Issue here open so that we can get back to it when TrajAn has matured a bit more

**Comment by erikvansebille** [comment]
This has been implemented in #1397, see e.g. https://docs.oceanparcels.org/en/latest/examples/parcels_tutorial.html#Reading-in-data-from-arbritrary-NetCDF-files
