### ISSUE TITLE
File output after multiple particleset.execute() calls

### ISSUE THREAD

**Issue by Jacketless** [OceanPARCELS/parcels#132]
At present it is very simple to call `particleset.execute()` within a loop (for example, when some calculation such as density is required between larger 'time-leaps'), and this results in a number of separate particle trajectory output files. Each `Particle` object in the set keeps it's lon/lat position between calls, so there is no need to create a new `particleset` object between calls to `execute()`.

However, I've realised that it's not so simple to 'stitch' these output files together post-hoc. Firstly, the starting position is re-written to the output file each time, which in this case will also be the final written position of the previous time-leap file.
In addition, the recorded timestamp of the first observation always appears to be zero, regardless of the `starttime` argument passed to the `particleset.execute()` call.
The unique particle ID suggested in issue #128 would also aid in correctly stitching multiple output files together.

Off the top of my head, this could be addressed by:

1. Leaving the user to remove duplicate observations themselves post-hoc (which is fairly trivial given the duplicate obs always has a timestamp of zero at present), or;
2. Adding a 'continue` argument to `particleset.execute()` calls, indicating the start positions do not need to be written to file for that call, or;
3. Adding a `started` boolean attribute to the `particleset` class, which is automatically flagged after the first instance of `execute()` being called, and automatically stops initial positions of particles being written in subsequent calls

**Comment by erikvansebille** [comment]
I agree that this is an issue, although there is already the option to flag `initial_dump=False` when creating a new `ParticleFile`. So that should make stitching much simpler.

The other option is simply to reuse the `ParticleFile` object. I.e. to call `pfile = ParticleFile(filename)` only once, before `.execute()`, and then in the for loop, write `pset.execute(..., output_file=pfile)`

However, none of these solutions work when particles are added or deleted in between calls to `.execute()` (i.e. when the size of pset changes). That is why I have been working on a solution to this too over the past few days. See commit c24abc2.

The way I solved it in c24abc2 (part of the Particlefile-Indexed branch; soon to be a PR), is to remove the initial_dump from `ParticleFile.__init__` altogether and instead call `pfile.write()` *before* the kernel execution in the `.execute()`

Now, particleFile is updated before kernel execution. Advantages are
- ‘Time’ of particles is known, so doesn’t have to be guessed as 0.
- Particles can be added/deleted in between `.execute()` calls
- Start locations of particles are always accurately written

Disadvantage of this implementation is that the last particle position will not be written. Since we never know when will be the ‘last’ one (as there can always be another call to .execute, I think the only solution is that users who want to also write the last particle positions do a final call to particle_file.write() at the end of their script

**Comment by erikvansebille** [comment]
Fixed in #137. Note that the disadvantage at the end of the previous comment is fixed in this PR. output will now be written both at the start and at the end of the .execute() call
