### ISSUE TITLE
Problem with the simulations outputs in .zarr format

### ISSUE THREAD

**Issue by JSoto-Nav** [OceanParcels/parcels#1336]
Hello,

I've been using parcels for a little while and up to now I had no problem using netCDF as extension for the outputs of the simulations. However, I have recently installed the model in a new computer and now I cannot use the netCDF outputs, I get this error messege when I try:

> RuntimeError: Output in NetCDF is not supported anymore. Use .zarr extension for ParticleFile name.

I've tried to change the file extension to .zarr, but them I get a different error:

> AttributeError: 'ParticleFileSOA' object has no attribute 'export'

I obtain an output that is not a file, but a folder. My questions are:
- Is there a way to get the outputs in netcdf format?
- If not, can I convert .zarr to netcdf in my code (I'm not very fluent in python)?
- How can I fix the Attribute Error?

Thank you in advance for your help.
J.

**Comment by VeckoTheGecko** [comment]
Hi @JSoto-Nav. As of [v2.4.0](https://github.com/OceanParcels/parcels/releases/tag/v2.4.0), `parcels` outputs trajectories in the zarr format instead of NetCDF.

Check out the latest version of the [Output Tutorial notebook](https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_output.ipynb) for more info. In brief, converting from zarr to NetCDF is very easy.

```py
import xarray as xr

...

output_file = pset.ParticleFile(name="Output.zarr", ...)
pset.execute(..., output_file=output_file)
# Trajectories are now in Output.zarr folder

data_xarray = xr.open_zarr('Output.zarr')
data_xarray.to_netcdf('Output.nc')


```

**Comment by JSoto-Nav** [comment]
Ok, thank you very much! I didn't see the output tutorial. Now is working :-)
