### ISSUE TITLE
recovery option diseapperaed

### ISSUE THREAD

**Issue by gmaze** [OceanParcels/parcels#1466]
Hi folks,
With the last release v3.0.0, the ``particleset.execute`` method argument ``recovery`` has been deleted

This is very annoying for the [VirtualFleet software](https://github.com/euroargodev/VirtualFleet) that was using it to customize Argo floats behavior when transported out of the domain (triggering change in, or constant cycle phase)

So, this issue to ask:
- why the option disappeared without a deprecation warning ?
- was there a rational to make the option disappeared at all ?
- is it possible to get the former behavior with the new `postIterationCallbacks` argument ?

Thanks for your answers !
g

ping @quai20

**Comment by gmaze** [comment]
the peace of code that was used before was in the [kenernalsoa.py execute method](https://github.com/OceanParcels/parcels/blob/2f35c21b9431039d5a49b235cd7b3e990e31d733/parcels/kernel/kernelsoa.py#L175C1-L180C38):

```python
        if recovery is None:
            recovery = {}
        elif ErrorCode.ErrorOutOfBounds in recovery and ErrorCode.ErrorThroughSurface not in recovery:
            recovery[ErrorCode.ErrorThroughSurface] = recovery[ErrorCode.ErrorOutOfBounds]
        recovery_map = recovery_base_map.copy()
        recovery_map.update(recovery)
```

but this has been removed in [v.3.0.0 in kernels.py](https://github.com/OceanParcels/parcels/blob/3662aa56d1c6652aaad504440c4f4df096fe7168/parcels/kernel.py#L553)

**Comment by erikvansebille** [comment]
Thanks for reporting, @gmaze. The recovery codes were indeed deprecated in v3.0.0, because their implementation was extremely inefficient/slow and there were no cases where what they did could not be done by 'normal' kernels in the new way that we implemented the Kernel loop.

All of this has been listed in the [release notes of v3.0.0](https://github.com/OceanParcels/parcels/releases/tag/v3.0.0) and specifically in the [Working with Status Codes section](https://docs.oceanparcels.org/en/latest/examples/tutorial_kernelloop.html#Working-with-Status-Codes) of the new [Kernel Loop tutorial](https://docs.oceanparcels.org/en/latest/examples/tutorial_kernelloop.html).

Could I encourage you to try implementing your recovery with normal Kernels? It will likely also speed up your code. 

Let me know if you need specific help. Since Parcels is actively-developed research software, it can at times still be rough around the edges. But the only way to improve it is to help each other :-)

**Comment by gmaze** [comment]
ok, great @erikvansebille and thank you for the explanation and for pointing out the new Status Codes 

we will try to update our software to work with the new version, and hopefully this could also improve performances !
and we'll surely raise issues if we can't work this out without more help, thanks 🤝
