### ISSUE TITLE
How to Output or Check Interpolation Results of u_uss and v_uss in Parcels Custom Kernel?

### ISSUE THREAD

**Issue by Cyuan-hub** [OceanParcels/parcels#1537]
Hi, @michaeldenes.
I have a question regarding the custom kernel “StokesDrag” in my simulation. In this function, I'm calculating u_uss and v_uss, and then using them to update the particle's longitude and latitude. I want to ensure that these interpolated results are correct. Could you please guide me on how to output or check the interpolation results of u_uss and v_uss?

Here's some of my code:
def DeleteParticle(particle, fieldset, time):  
    particle.delete()
    print (str(particle.id) + ' is deleted at '+ str(particle.lon) + ' and ' + str(particle.lat))

def Ageing(particle, fieldset, time):
    particle.age += particle.dt

def StokesDrag(particle, fieldset, time):
    (u_uss, v_uss) = fieldset.UVuss[time, 0, particle.lat, particle.lon]
    particle.lon += u_uss * particle.dt
    particle.lat += v_uss * particle.dt
    
Kernels= [StokesDrag, Ageing]

import zarr
out_interval = timedelta(days = 1)

new_output_directory = "G:/JupyterNotebook/SCS_case2/ParcelsOutput/ZarrData/"
output_dirstore_name = new_output_directory + "StokesDrag_Ageing-1month.zarr/"
output_dirstore = zarr.storage.DirectoryStore(output_dirstore_name)

outputfile = pset.ParticleFile(name=output_dirstore, outputdt = out_interval)

dt = timedelta(minutes = 30) 

totaltime_for_running = timedelta(days = 31)
running_time_first = timedelta(days = 21) 

pset.execute(Kernels,
             runtime = running_time_first,
             dt = dt,
             output_file = outputfile,
             recovery = {ErrorCode.ErrorOutOfBounds: DeleteParticle, 
                         ErrorCode.ErrorTimeExtrapolation: DeleteParticle})

pset.repeatdt = None

pset.execute(Kernels,
             runtime = timedelta(days = 10), 
             dt = dt, 
             output_file = outputfile, 
             recovery = {ErrorCode.ErrorOutOfBounds: DeleteParticle, 
                         ErrorCode.ErrorTimeExtrapolation: DeleteParticle})

**Comment by michaeldenes** [comment]
Hi @Cyuan-hub, sorry I didn't get to this sooner. I would probably post this in the discussion section rather than as a Parcels issue, but that's for next time.

Your code looks okay to me, however, it's hard to determine without seeing what the fieldset creation looks like. You can look at what your velocities should be by sampling `fieldset.UVuss` at a specific location and time (like you do in your kernel).

If sampling like you are in your kernel, then you should expect the result (the `u` and `v` velocities) to be in units of degrees per second, in the east and north directions respectively. Then updating your particle positions in lat/lon space is correct (with the Euler-forward scheme you are using)

If you try `fieldset.Wind_U.eval(time, depth, lat, lon, applyConversion=False)` (using the same time, depth, lat, and lon as above), then you should expect values in meters per second, and in the `i` and `j` directions of your model grid.

If either of these look wrong, then you may have a problem. But that is probably solved with the far better description of fieldset sampling in this tutorial on the Parcels page: https://docs.oceanparcels.org/en/latest/examples/tutorial_unitconverters.html

I'm closing this issue with this comment, but if you have more questions, feel free to ask them in the discussions section.

Cheers,
Michael

**Comment by Cyuan-hub** [comment]
> Hi @Cyuan-hub, sorry I didn't get to this sooner. I would probably post this in the discussion section rather than as a Parcels issue, but that's for next time.
> 
> Your code looks okay to me, however, it's hard to determine without seeing what the fieldset creation looks like. You can look at what your velocities should be by sampling `fieldset.UVuss` at a specific location and time (like you do in your kernel).
> 
> If sampling like you are in your kernel, then you should expect the result (the `u` and `v` velocities) to be in units of degrees per second, in the east and north directions respectively. Then updating your particle positions in lat/lon space is correct (with the Euler-forward scheme you are using)
> 
> If you try `fieldset.Wind_U.eval(time, depth, lat, lon, applyConversion=False)` (using the same time, depth, lat, and lon as above), then you should expect values in meters per second, and in the `i` and `j` directions of your model grid.
> 
> If either of these look wrong, then you may have a problem. But that is probably solved with the far better description of fieldset sampling in this tutorial on the Parcels page: https://docs.oceanparcels.org/en/latest/examples/tutorial_unitconverters.html
> 
> I'm closing this issue with this comment, but if you have more questions, feel free to ask them in the discussions section.
> 
> Cheers, Michael



> Hi @Cyuan-hub, sorry I didn't get to this sooner. I would probably post this in the discussion section rather than as a Parcels issue, but that's for next time.
> 
> Your code looks okay to me, however, it's hard to determine without seeing what the fieldset creation looks like. You can look at what your velocities should be by sampling `fieldset.UVuss` at a specific location and time (like you do in your kernel).
> 
> If sampling like you are in your kernel, then you should expect the result (the `u` and `v` velocities) to be in units of degrees per second, in the east and north directions respectively. Then updating your particle positions in lat/lon space is correct (with the Euler-forward scheme you are using)
> 
> If you try `fieldset.Wind_U.eval(time, depth, lat, lon, applyConversion=False)` (using the same time, depth, lat, and lon as above), then you should expect values in meters per second, and in the `i` and `j` directions of your model grid.
> 
> If either of these look wrong, then you may have a problem. But that is probably solved with the far better description of fieldset sampling in this tutorial on the Parcels page: https://docs.oceanparcels.org/en/latest/examples/tutorial_unitconverters.html
> 
> I'm closing this issue with this comment, but if you have more questions, feel free to ask them in the discussions section.
> 
> Cheers, Michael

Hi, @michaeldenes.

Thank you for your guidance and for taking the time to provide insight into my question. Your guidance has been incredibly helpful, and I'll make sure to explore the tutorial on fieldset sampling to enhance my understanding further.

Thanks once again for your support!

Best regards,
Cyuan
