### ISSUE TITLE
Certain dtypes for `Variable` objects cause particleset.execute to hang

### ISSUE THREAD

**Issue by Jacketless** [OceanPARCELS/parcels#182]
Today I've managed to track down a bug which has been causing particleset execution loops to hang at the first iteration of the interval loop.

The cause was having defined a particle `Variable` object as having `dtype=np.int8` (it was for a simple flag variable, so I was trying to save memory). It seems this dtype is not implemented or throws and error when referenced in a Kernel in JIT mode. No warning is given during compilation of the Kernel. Other integer types work fine: np.int16 works, for example.

Perhaps there could be a check for implemented dtypes, and/or at least a list of supported dtypes for custom particle variables given in PARCELS tutorials?

**Comment by erikvansebille** [comment]
Hi @Jacketless, sorry for taking so long to respond to this bug report. However, are you sure the issue is the `dtype=np.int8`? Because when I added a test for a `dtype=np.int8` to `test_particles.py` (see the `expand_dtype_options_in_Variable` branch) everything seems to work.

Are you perhaps running an old version of parcels? Because PR #137 had a fix for a misalignment bug between float64 and float32 (commit 0d7d2c1) that sounds similar to this bug?

Let me know if the issue still persists after confirming that you're running with the #137 fix, and if `py.test tests/test_particles.py` on the `expand_dtype_options_in_Variable` branch works. I'll have another look then!

**Comment by erikvansebille** [comment]
Actually, I now realise that this is a bug. The issue is not the initialisation of the ParticleSet, but its execution. Adding the line `pset.execute(AdvectionRK4, runtime=1., dt=1.)` to the `test_variable_init()` test leads to a segmentation fault on the `expand_dtype_options_in_Variable` branch. Will investigate further!

**Comment by erikvansebille** [comment]
As of #186, Parcels gives an error for unsupported `dtypes`
