### ISSUE TITLE
Model data starting at year 0000-01-01

### ISSUE THREAD

**Issue by guidov** [OceanParcels/parcels#220]
days since 0000-01-01 00:00:00' ValueError: year is out of range

I ran into this problem with ocean model data starting at year 0000 with a standard noleap calendar.

Don't have a good work around for this right now. 

See description of the issue here: https://github.com/Unidata/netcdf4-python/issues/442

**Comment by erikvansebille** [comment]
This looks much like a bug in the unidata netcdf python library, and might be resolved when we move to dask (Issue #216)?

In the meantime, a work-around could be to read in the data using the netcdf Dataset directly, and then use `FieldSet.from_data` (instead of the shortcut `FieldSet.from_netcdf` method)

**Comment by erikvansebille** [comment]
This is now explicitly dealt with through PR #353; Parcels indeed only supports `time_origins` between 1678 and 2262, and throws an error if time_origin is outside. Closing this issue and #220 for now, until we hear about a actual use-case for extending this date range (which would be a lot of work!)
