### ISSUE TITLE
Local variable 'time_origin' referenced before assignment

### ISSUE THREAD

**Issue by atadbrad** [OceanParcels/parcels#222]
While going through the Animated Gif tutorial, trying to run ln 5 results in the error message in terminal below. It compiled and saved the first particles.png, but without the added 00 string at the end. I copied/pasted everything from the tutorial. Running Mac OS X El Capitan V 10.11.6.

> INFO: Plot saved to particles.png
> INFO: Visualisation is not possible. Basemap not found.
> Traceback (most recent call last):
>   File "tutorial.py", line 34, in <module>
>     pset.show(field='vector')
>   File "/Users/User/parcels/parcels/particleset.py", line 417, in show
>     if time_origin is 0:
> UnboundLocalError: local variable 'time_origin' referenced before assignment

**Comment by erikvansebille** [comment]
Thanks for reporting this Issue @atadbrad! The main problem seems to be that you don't have the `Basemap` package installed, even though the Animated Gif tutorial depends on that. How did you install Parcels? Because it should try to install `Basemap` automatically..

Nonetheless, the error you're getting about the time_origin is a bug and I will try fix it. Will create a pull request soon.
