### ISSUE TITLE
Is it possible to apply parcels at a dataset of a certain time period for multiple times?

### ISSUE THREAD

**Issue by pdnooteboom** [OceanParcels/parcels#229]
I am working at a 3D case similar to the corefootprint particles example:
https://github.com/OceanParcels/Parcelsv0.9Paper_Scripts/blob/master/experiment_scripts/example_corefootprintparticles.py
Suppose you want to use one year of data in this corefootprint particles example multiple times. Is this possible? So for example to use the data from the year 1980 three times to track a particle for three years.

I am now getting as far as adding snapshots of the same year the second time with fieldset.advancetime() method and get:
RuntimeError: Time of field_new in Field.advancetime() overlaps with times in old Field

**Comment by erikvansebille** [comment]
Thanks @pdnooteboom. In the short term, the way to fix the RuntimeError is to also change the `fieldset.U.time` (and `fieldset.V.time` etc) so that they 'count through'

In the longer term, it might be nice to implement this 'looping' of velocity fields as an option, for example through the `allow_time_extrapolation=looping` attribute in `FieldSet`. The could be a useful feature for some users

**Comment by pdnooteboom** [comment]
Thanks @erikvansebille!
