### ISSUE TITLE
Different ways of saving particle data

### ISSUE THREAD

**Issue by pdnooteboom** [OceanParcels/parcels#260]
Currently I only found one method to save the data of particles, which saves all trajectories of all particles.
However, could it be nice if the code incorporates different ways of saving data? Then you can save data in a more efficient way.

For instance, I am tracking a sinking particle in 3D back in time, which is released at the bottom. I only need the data of this particle once it reaches the ocean surface. I do not need all the data during the whole trajectory of any particle.

**Comment by erikvansebille** [comment]
Very nice idea, @pdnooteboom. The case you describe, where only the particle data on the last time needs to be written, could be implemented through e.g. a `to_write=last`, similar to what @davidwichmann implemented in #252. However, implementation of this will be nontrivial. I see two options:

1. We could add an extra argument to the last time `pfile.write()` is called in `.execute()`, as that happens outside the main `for`-loop. But this would not work if there is an extra `for`-loop in the user-script, e.g. for `.advancetime()`. 
Furthermore, users can invoke this type of behaviour already by either setting `interval` to a very large number, or by explicitly calling `pfile.write()` in their script after the `.execute()` has finished. 

2. But the biggest problem with implementation 1 is that it will not deal with particles that are deleted halfway a run. A more interesting alternative therefore is to only write particles that are deleted (`to_write=on_delete`?). I think that technically that should be feasible. 
However, we need to make a choice whether individual `Variables` can be set to `to_write=on_delete`, or whether all `Variables` are written in the same way. This matters, because by default variables like `lon` and `lat` are initialised with `to_write=True`. I guess a typical user would want *all* `Variables` to be written `on_delete`, not just the custom ones.

So perhaps the way to implement this is with an additional argument to `ParticleFile` initialisation to flag that *all* `Variables` (except those where `to_write=False`) only need to be written when a `Particle` is deleted? Would that work for your use-case, @pdnooteboom?

**Comment by delandmeterp** [comment]
Maybe @erikvansebille we could also do the following idea:

We don't always want to delete particles when they reach the surface or are out of boundary. We could also give them a flag 'killed' (not 'dead', because it could be used by people carrying living particles).
A killed particle stays in the pset, but is frozen, which means that none of its states (neither the time nor anything else) can be edited.

Then, at the end of its script, the user could for example do the pfile.write(writeParticles='All'), which would mean that he would print the variables with flag to_write=True and to_write='last'

This also gives a lot of freedom to do any post-pro with all the particles within the same script.
The disadvantage is that all particles stay in memory. To have an idea of this potential problem, could you @pdnooteboom have an idea or what is the ratio len(pset.particles) / pset.particles[-1].id ?

**Comment by pdnooteboom** [comment]
This sounds like a good solution for my case @erikvansebille!

Only one thing we have to consider, is that the data only needs to be written if particles reach the surface, not if they get deleted for another reason such as going out of their horizontal boundaries. 
So the particles should only be written if deleted by a specific kernel, not when they are deleted in general.

**Comment by delandmeterp** [comment]
We discussed the problem in the office,
And this is another solution (with no extra cost):

A particle has an variable killed = 0
When a particle gets out of boundary, we put it to killed = 1
In the next iterations, particles with killed = 1 are completely ignored
Next time pfile.write is called particles with to_write=last and killed=1 are written (and also with to_write=True). Also if killed=1, then killed=2
In each iterations, particles with killed=2 are removed.

The seems feasible to write, has no extra-cost (actually it has, but it is reasonable, if writing is done often enough), but it means no post-pro in the same file for all particles.
Post-pro should be done in another file using the nc file as an input
