### ISSUE TITLE
Field.from_netcdf does not work for variables with less than 3 dimensions

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#267]
Currently, the `Field.from_netcdf()` function assumes a NetCDF variable has either 3 or 4 dimensions (lines 275-278 of field.py)
```
if len(filebuffer.dataset[filebuffer.name].shape) is 3:
    data[tidx:tidx+len(tslice), 0, :, :] = filebuffer.data[:, :, :]
else:
    data[tidx:tidx+len(tslice), :, :, :] = filebuffer.data[:, :, :, :]
```

This means Parcels won't work with NetCDF variables that have two dimensions (or more than 4). It should be fixed

**Comment by delandmeterp** [comment]
Indeed, I for example need to read a 2D array for curvi grids, and the fix comes in this branch.

For 1D or >4D arrays, it does not work but there is currently no point, since there is no interpolator for such data. Apart from our rectilinear and curvilinear grids, we might also have for example vertical grids, with 1D (or 2D if time is here) data. But we don't have such data for the moment

**Comment by delandmeterp** [comment]
Curvilinear branch, which includes 2D arrays, was merged into master and solves this problem.

However, In further development, it will be important to make a distinction between 2D x-z arrays and x-y arrays for example. For the moment, all kinds of grids supported by interpolation schemes can be read using `Field.from_netcdf()`
