### ISSUE TITLE
Include numpy probability distribution sampling functions in code generator

### ISSUE THREAD

**Issue by Jacketless** [OceanPARCELS/parcels#27]
It would be great to be able to use the numpy.random distribution functions for random walks and other behaviours, but I believe they are not yet supported in the JIT code generator. In particular random.uniform, random.normal and random.power would be pretty sweet to be able to use.

(Not sure if raising an issue is appropriate without having discussed first, but I guess this is one way to get to know our github workflow!)

**Comment by mlange05** [comment]
First of all, yes, raising an issue is exactly the right thing to do. This way anyone can follow the conversation and contribute with comments and suggestions.

Now for the Pseudo Random Number Generation (PRNG) problem I'm not quite sure how to proceed, since there are several ways we could go. Here are a few ideas:
* Use the standard C function `srand` in JIT mode and add the boilerplate code to adjust for range and sampling from non-uniform distributions. The basic PRNG would be reasonably fast to implement, but some of the more advanced uses might become tedious to code.
* Use a fast RNG, like a Mersenne Twister algorithm (eg. [this one](https://www.cs.hmc.edu/~geoff/mtwist.html)). This is probably the right thing to do in terms of speed and computational efficiency, but it does mean we're relying on some external code and adjusting for range and distribution might become tedious.
* Use Numpy's C-API directly. This would somewhat guarantee that we do the same thing in both modes, but it might become a pain to implement and might not be the fastest. I'll have to dig deeper to see how painful it really becomes.

Another problem that we have to think about is how we do this in parallel, especially considering how to keep the PRNG sequence reproducible with different numbers of processors. Any ideas and suggestions are welcome.

**Comment by mlange05** [comment]
Ok, I should really read and follow my own links. Turns out someone wrote a really nice PRNG package called [PCG](http://www.pcg-random.org/) and put a [minimal C implementation of their RNG](http://www.pcg-random.org/download.html) on the website. I think this looks like a good place to start for the JIT mode.

Another consideration would be that, since PCG is sightly different to the numpy's RNG, we might want to think of introducing an intrinsic like `ParcelsRNG()` that defers to either `numpy.random` or PCG depending on the execution mode.

**Comment by erikvansebille** [comment]
This PCG looks good indeed, I agree this would be a good way to start

**Comment by Jacketless** [comment]
That's great- given the suite of RNGs and the fact there's a C
implementation, what a good find.

**Comment by Jacketless** [comment]
Just a gentle nudge on this issue, sorry to be a pain. I'm now at the stage of running some early tuna simulations with quite a few particles, and if I could run them in JIT mode it would really save me a lot of time.

I really only need an equivalent of `numpy.random.uniform()` and I would be set for a while yet. It seems that the [http://www.pcg-random.org/using-pcg-c-basic.html](minimal C random stuff) has something that would work. Any chance of implementing this JIT functionality @mlange05 ??

**Comment by mlange05** [comment]
PR #82 should address this. I would be really keen to see some Parcels code that actually simulates tuna. :wink:

**Comment by Jacketless** [comment]
Amazing- thanks a lot for implementing this @mlange05. I'm really hoping I can speed up my tuna runs by running in JIT soon

I know you're keen to see the tuna-parcels code, I promise I'm not hiding anything on purpose! Now that the parcels master is getting close to having all the functionality I need I will start putting together a separate repository for animal movement model, rather than working from incomplete parcels branches. I'll get it to you guys real soon! 🐟🐟
