### ISSUE TITLE
FieldSet.from_data .show() bug

### ISSUE THREAD

**Issue by HandmannP** [OceanParcels/parcels#298]
Dear everybody,
Apparently the .show() method after importing a field with FieldSet.from_data does not work. I did the following:

for loading .mat files :
import scipy.io
import matplotlib.pyplot as plt
import cmocean
for parcels :
from parcels import FieldSet, ParticleSet, JITParticle, ParticleFile, plotTrajectoriesFile
from parcels import AdvectionRK4, timer
import numpy as np
from datetime import timedelta, datetime
import netCDF4 as nc4

mat = scipy.io.loadmat('/UVgrid_full.mat')
lon_argo =  np.arange(-65, 0.5, 0.5, dtype=np.float32)
lat_argo =  np.arange(45, 65.25, 0.25, dtype=np.float32)
depth = np.zeros(1, dtype=np.float32)
time = np.zeros(1, dtype=np.float64)
U_argo = mat['U']
V_argo = mat['V']

make mask for U and V:
mask_UV = np.ma.masked_invalid(U_argo)
U_argo_mx = np.ma.masked_array(U_argo, mask=mask_UV.mask)*1/100
V_argo_mx = np.ma.masked_array(V_argo, mask=mask_UV.mask)*1/100
speed_argo = (U_argo_mx**2+V_argo_mx**2)**0.5 

cmap=cmocean.cm.balance
Upl=plt.contourf(lon_argo, lat_argo,U_argo_mx,50,
                 vmin=-0.2, vmax=0.2,cmap=cmap,
                 extend='both')
cbar=plt.colorbar(Upl)
cbar.ax.set_ylabel('[m/s]')
plt.show()

![unknown_2](https://user-images.githubusercontent.com/16838898/36414609-2bffd36a-1623-11e8-937d-4c9fd5dc6e38.png)

Parcels fieldset:
data = {'U': U_argo_mx,
        'V': V_argo_mx}
dimensions = {'lon': lon_argo,
              'lat': lat_argo,
              'time': time,
              'depth': depth}
field_set = FieldSet.from_data(data, dimensions,mesh='spherical', allow_time_extrapolation=True)

compute speed:
speed = field_set.U
speed.data = (field_set.U.data**2+field_set.V.data**2)**0.5  

field_set.U.show()

![unknown](https://user-images.githubusercontent.com/16838898/36414601-24a6fdc8-1623-11e8-9325-89a2a39a41e7.png)

Then I advect Particles with the base kernel:

pset = ParticleSet.from_list(fieldset=field_set, pclass=JITParticle, lon=[ -51,  -51],lat=[55, 56]) 
pset.execute(AdvectionRK4, runtime=timedelta(days=6), dt=timedelta(minutes=5), output_file=pset.ParticleFile(name="EddyParticles", outputdt=timedelta(hours=1))) 

The advection works - the particle position changes but still the pset.show() does not work
- pset.show() gives the same noisy output

**Comment by delandmeterp** [comment]
How big is you UVgrid_full.mat file? Could you drop it here, or send me a link to it?
It would help me to see what is going on and to work on fixing the problem!

**Comment by HandmannP** [comment]
Dear Philippe,

Here is the file. thank you for your time and fast response!



Cheers,
Patricia

**Comment by delandmeterp** [comment]
So the problem is that your original data was transposed compared to the one the code expects. And instead of complaining the code was reshaping wrongly your data, leading to the wrong plot (and wrong results in your pset.execute)

Such reshaping is not possible in current version of the master branch (you were using an older version of the code). We will update the code such that the error message will be more explicit.

In current version, Parcels throws an error in your case. You then have to replace your field_set creation by this line.

field_set = FieldSet.from_data(data, dimensions,mesh='spherical', allow_time_extrapolation=True, transpose=False)


@willirath, you might also be interested by using the newest version of the code, to avoid such issue.
