### ISSUE TITLE
RK4 time dependence

### ISSUE THREAD

**Issue by Abobie** [OceanPARCELS/parcels#31]
I noticed that when taking a step with the RK4 method in `particle.py` it uses the velocities at different points in the grid as it should, but always at the starting time of the step. In python I could easily adjust it to take velocities at `t=time+dt/2` or `t=time+dt` where it should, but JIT still uses only `time` as an argument when calling `temporal_interpolation_linear`.

Also, I'm still trying to get used to using github... Is there an easy way for me to push just the changes I made in `particle.py`? I'm currently working in the numerics branch I made, and I have things there that I don't want to push along with it yet. I'm not even sure if I should have added the analytical eddies test to the branch or just kept it locally to play with...

**Comment by mlange05** [comment]
Good find! We were indeed dropping the kernel-defined time indices on the floor in JIT mode. The fix is in PR #32 and should be merged soon.

For the git question, the right thing to do here is to create multiple branches, one for the stuff that is ready to be uploaded and a local one for any experimental changes. Utility functions like `git rebase` and `git cherry-pick` can help you to maintain and move commits between those. That being said, there is no good reason to keep things purely local, since we do not require all branches to be merged and it is usually better to work openly and keep your work backed up on github.

**Comment by mlange05** [comment]
I believe this has been fixed now, so closing the issue.
