### ISSUE TITLE
Using parcels on POP grid

### ISSUE THREAD

**Issue by TMorrison27** [OceanParcels/parcels#325]
Hello,

I am trying to use parcels on a tri-pole POP grid. What is the best way to set up the mesh option in feild.from_data? The data I have includes corrections angles for u and v near the poles. If I pre-rotate the velocities, would I then be able to just use the flat option of mesh?

-Theresa

**Comment by erikvansebille** [comment]
Hi Theresa,

If POP already comes with the rotation angles for U and V, then you should be able to provide these to Parcels, so that the rotation is done automatically on the fly for you. You can use the `FieldSet.from_netcdf()` function for this, but will need to add the angle fields as extra entries to the `variables` dictionary. E.g. (for the NEMO defaults; these names are probably different in POP):
```
filenames['cosU'] = rotation_angles_filename
filenames['sinU'] = rotation_angles_filename
filenames['cosV'] = rotation_angles_filename
filenames['sinV'] = rotation_angles_filename

variables['cosU'] = 'cosU'
variables['sinU'] = 'sinU'
variables['cosV'] = 'cosV'
variables['sinV'] = 'sinV'

dimensions['cosU'] = {'lon': 'glamu', 'lat': 'gphiu'}
dimensions['sinU'] = {'lon': 'glamu', 'lat': 'gphiu'}
dimensions['cosV'] = {'lon': 'glamv', 'lat': 'gphiv'}
dimensions['sinV'] = {'lon': 'glamv', 'lat': 'gphiv'}
```
This is probably easier than pre-rotating the velocity fields yourself; but it would be good to confirm that this gives the same results as the pre-rotated fields. This is the first time, I think, that Parcels is run on tripolar POP...
Let us know how you go, and happy to help further; good luck!

**Comment by fischcheng** [comment]
I'm definitely interested in testing this out and would love to see Parcels to work with POP. For the record, I did pre-rotate all my CESM/POP outputs first into regular grid before feeding them into CMS. However, from my experience, I think POP only comes with the "weight files" (https://www.ncl.ucar.edu/Applications/popwgtfiles.shtml), not just the rotation angles.

**Comment by erikvansebille** [comment]
OK, thanks @fischcheng. Note that Parcels can also do rotation itself (see https://github.com/OceanParcels/parcels/blob/master/parcels/scripts/compute_curvilinearGrid_rotationAngles.py), although this code is modelled on the NEMO tripolar grid so not sure if this also works for POP. 

If you want to give it a try, then follow the directions on the [NEMO curvilinear grid tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_nemo_curvilinear.ipynb)
