### ISSUE TITLE
Initialization of particle-variables fails if working with fieldset-lists (instead of advance_time)

### ISSUE THREAD

**Issue by davidwichmann** [OceanParcels/parcels#346]
In the new parcels version the field.advancetime() was replaced by loading a list of fields in the beginning, but these fields are according to @delandmeterp  created in the particle execution. For a new particle class with user defined variables based on a field, the initialization of the variable is done in the pset creation, i.e. before the execution, and fails with error "TypeError: 'NoneType' object has no attribute '__getitem__'".

**Comment by erikvansebille** [comment]
Hmm, this is a bug indeed. Thanks for reporting, @davidwichmann!  

I've coded up a proof-of-concept in example_globcurrent.py at
https://github.com/OceanParcels/parcels/tree/particle_init_field_deferred_loafing_bug, see also below
```
@pytest.mark.parametrize('mode', ['scipy', 'jit'])
def test_globcurrent_variable_fromfield(mode):
    fieldset = set_globcurrent_fieldset()

    class MyParticle(ptype[mode]):
        sample_var = Variable('sample_var', initial=fieldset.U)
    pset = ParticleSet(fieldset, pclass=MyParticle, lon=[25], lat=[-35], time=fieldset.U.time[0])

    pset.execute(AdvectionRK4, runtime=delta(days=1), dt=delta(minutes=5))
```
This indeed fails because of the error you mentioned. We can use this branch to bug-fix
