### ISSUE TITLE
Implement vertical velocities 

### ISSUE THREAD

**Issue by erikvansebille** [OceanPARCELS/parcels#39]
Currently, parcels can only advect in 2D (horizontal) flow. However, for many applications particles will need to be tracked in 3D. 

This is actually quite a critical functionality, which once we have it will allow much more uptake in the physical oceanographic community

This will require an extension of the advection functions, but should for the rest be relatively straightforward?

**Comment by erikvansebille** [comment]
I started working on the vertical velocities today, but quickly hit a (what I think is a) pretty major roadblock.

I've committed changes to test_particle that allow creation of multiple depth layers in the netcdf files. That was easy. However, making parcels read these fields is much more tricky

The problem, I think, is that we are using `scipy.interpolate.RectBivariateSpline` in field.py (line 96) and that this function as it names suggests can only handle 2D fields. There does not appear to be a TrivariateSpline.

I've looked around, and scipy also has the `scipy.interpolate.RegularGridInterpolator` function, but that will require significant rewriting to work. Plus, this function only works on regular grids, so we will again hit a roadblock once we go to irregular grids.

Another option is to assume that grids are always staggered in the vertical (this is a good assumption, I've never seen an ocean model which where vertical grid cells are not column-wise on top of each other). If we assume this, we could treat the interpolation in the vertical separately: interpolate the grid level above and below the particle in 2D, and then vertically interpolate between these two points. Does this make sense?

Any ideas how to progress from here very welcome! 3D tracking of particles is a pretty major enhancement which we will absolutely need for the GMD manuscript

**Comment by erikvansebille** [comment]
Following up on my comment earlier today, what I suggested with the separate treatment of vertical direction from the horizontal direction is equivalent to how interpolation in time is treated. So we could build on that code

**Comment by mlange05** [comment]
Ok, I propose that we eventually want to do both for the GMD manuscript, since one of parcel's major abstractions is the generic interaction with different types of grids and different interpolation methods. I like the idea of using `scipy.interpolate.RegularGridInterpolator`, since it uses trilinear interpolation and should thus be almost perfectly equivalent to what we do in JIT mode. Similarly though, I also would like the opportunity to treat vertical interpolation separately, since I can see various reasons and use cases for this too. 

The key thing to consider, I believe, is how do we define the internal data layout within a `parcels.Grid` and how to let the various grid flavours (eg. `parcels.Grid3D` or `parcels.Grid2DExtruded`) inherit the various generic methods while using different interpolation routines in Python and JIT mode. We also need to consider future additions of more complex grid classes, ie. `parcels.GridIrregular`, so carefully design is essential here.

**Comment by erikvansebille** [comment]
Completed implementation in #183
