### ISSUE TITLE
Constant field in JIT kernel

### ISSUE THREAD

**Issue by delandmeterp** [OceanParcels/parcels#441]
Such kernel is not processed in JIT mode:

```
def UpdateP(particle, fieldset, time, dt):
    constant = fieldset.constant
    particle.p = fieldset.P[time, particle.lon, particle.lat, particle.depth]
```

To make it work, variable `constant` must have a different name: `c = fieldset.constant`

**Comment by erikvansebille** [comment]
I don't think this is something that needs to be fixed. The error thrown in jit-mode it pretty obvious (see below). It would require a significant amount of work to catch this in our compiler, with only limited benefit. 

Since the workaround for users is trivial (just renaming their variables), I suggest we not fix this

```
Log output: /var/folders/r2/8593q8z93kd7t4j9kbb_f7p00000gn/T/parcels-501/b3dcc894d05411a8fb0b91f5f7c3f2d7.c:44:9: 
error: redefinition of 'constant'
  float constant;
        ^
/var/folders/r2/8593q8z93kd7t4j9kbb_f7p00000gn/T/parcels-501/b3dcc894d05411a8fb0b91f5f7c3f2d7.c:42:85: note: previous definition is here
static inline ErrorCode UpdateP(JITParticle *particle, double time, float dt, float constant)
                                                                                    ^
```
