### ISSUE TITLE
Initiate particleset particle positions from field

### ISSUE THREAD

**Issue by Jacketless** [OceanPARCELS/parcels#46]
Last week I roughly coded up the ability to define inital starting positions of the particles in a particle set from a distribution specified in one of the grid fields. I'd like to clean that code up and commit. Anyone have any alternative ideas about how to do this? 
At present, users specify the name of the field that they wish to use in place of the usual start lat,lon numerical argument. Then particleset tries to distribute the requested number of particles

**Comment by Jacketless** [comment]
oops, sorry submitted before I'd finished typing! 

...the number of particles are distributed across density map given by the start field.

**Comment by erikvansebille** [comment]
Yes, I like the idea! It's not super-critical, but it might be a nice feature indeed. So you're thinking of a Monte Carlo sampling of `p` particles based on some weighing function given by a grid file?

In general, it would be good to slowly start building a set of release functions. Just as we hope to have a library of kernels, we could also support a library of release functions. @mlange05, would it make sense to put these in separate directories? So `parcels/kernelfunctions` and `parcels/releasefunctions`? Or even in separate repositories? We want these sets of functions to become community resources, of course

**Comment by mlange05** [comment]
@Jacketless As discussed, I would do something like `ParticleSet.from_density_field(field, mode='linear')`, where field is a `parcels.Field`. This delegates the definition of the density function to the usual constructors, from file or otherwise.

@erikvansebille I'm not sure I fully understand what you mean by "release function", but I am guessing it's what I've called the `mode` argument in the above example. If that is the case I would argue that you will rarely need more than modes `linear` or `random`, which I would simply hard code. Creating a whole new class of custom functions sounds like overkill to me, at least until we have more detailed use-cases.

That being said, I do like the idea of moving our built-in kernels to `parcels/kernelfunctions`.

**Comment by erikvansebille** [comment]
@mlange05 sorry for the confusion, I meant _particle-release-event function_ when I said release function. The idea is that users can write their own high-level functions/kernels that take geographical information and create a ParticleSet. So it's more than the `mode` argument; it's the entire routine

Examples would include
`from_density_field`
`on_line `
`on_horizontalgrid`
`on_verticalgrid`
`on_verticalgrid_transportweighted`
etc

The last one is one that Ariane also includes; distribute a set of particles over a vertical grid so that they all cary the same transport (defined as local velocity times grid area).

**Comment by mlange05** [comment]
I still don't see the need for a library of event functions, merely a set of smart convenience constructors for `ParticleSets`. Also, don't we already do the equivalent of  `on_line` with the `start`/`finish` constructor?

**Comment by erikvansebille** [comment]
Yes, we indeed have the `on_line` already. My point is that this is something where I see the community contribute a lot of new 'smart convenience constructors'. The possibilities for creating `ParticleSets` are endless, so we may want to have a library of them for the community to easily browse. Just like they can browse kernels. I feel it would be easier to supply documentation if all these constructers are listed in one place

Anyway, we don't need to resolve this now; we can always move these constructors later, if you're not convinced yet. Or keep as is ;-)

Key is that @Jacketless should indeed create a `ParticleSet.from_density_field(field, mode='linear')` function. Good idea!

**Comment by mlange05** [comment]
I would argue we already allow anyone to build their own, since we expose `ParticleSet(lon=my_xarray, lat=my_yarray)`. Using this API, grid-aligned construction becomes a simple call to `numpy.meshgrid(grid.U.lon, grid.U.lat)`, no? But you are right, we are digressing, and `from_density_field` is an important functionality. :smiley:

**Comment by Jacketless** [comment]
Basic form of this functionality now implemented in #49
