### ISSUE TITLE
grid for particle variables and start_field on curvilinear grid

### ISSUE THREAD

**Issue by schmidt-christina** [OceanParcels/parcels#484]
I am releasing particles in a shelf region on a curvilinear grid. I use ParticleSet.from_field to release particles in gridboxes next to land. During execution I sample the variable 'ocean' that was initialised by tmask, the tracer interpolation method is linear. I experienced a mismatch between the variable ocean of each particle and the tmask. A short example is given in the attached pdf  file where I modified the curvilinear grid tutorial. -->Question: on which grid is the variable p.ocean and the release mask defined? When creating the field_set, I defined them on a T_grid.

[tutorial_nemo_curvilinear_modified.pdf](https://github.com/OceanParcels/parcels/files/2510539/tutorial_nemo_curvilinear_modified.pdf)

**Comment by delandmeterp** [comment]
Hi Christina,

There were various problems in Parcels, with both the plotting of fields and the `ParticleSet.from_field()` function.
Both those problems should be fixed by PR #495 and #496. (not yet in master)

Indeed, as you proposed, p.ocean and other tracer fields on a C-grid should be defined on the T_grid
(https://www.nemo-ocean.eu/doc/img360.png),
which is done automatically by the `fieldset.from_nemo()` function.

In the attached figure, you can see that particles are released in the desired cells.

![pset_from_field2](https://user-images.githubusercontent.com/31093031/49008053-3522c300-f16d-11e8-8ee8-434825e1005f.png)

**Comment by delandmeterp** [comment]
Both PRs were pushed to master.

**Comment by schmidt-christina** [comment]
Hi Philippe,

thanks for your work. I tried it again with my example notebook and the release in t-grid cells now works. However, as the f-gridpoint is defined at the upper right corner on a NEMO C-grid which is in contrast to plt.pcolormesh, the release position of particles is now shifted up and right by one gridbox (see attched figure where the asterix remarks the gridbox where I want to release)

![mismatch_between_releasepositions](https://user-images.githubusercontent.com/38216156/49082315-c4050d80-f249-11e8-857e-d23f2e06f052.png)

**Comment by delandmeterp** [comment]
Hi Christina,

This problem comes from the definition of the cell you expect to put your particles in.
See this small code:
```
import matplotlib.pyplot as plt
import numpy as np

lon, lat = np.meshgrid([0,1], [0,1])
val = np.array([[0,1],[2,3]])

plt.pcolormesh(lon, lat, val)
plt.colorbar()
plt.show()
```
It will plot value 0 in the element.
So, pcolormesh plots in a cell ranging from indices (j,i) to (j+1,i+1) the value val(j,i)
What we want, using the indices defined for the NEMO grids, is to plot value(j+1,i+1)

This is the format we use in Parcels, according to the format of nemo grids
Cell (j,i) has the 4 nodes (j,i), (j,i+1), (j+1,i+1)
The tracer in cell (j,i) is T(j+1,i+1)
The u values on left and right are u(j+1,i) and u(j+1,i+1)
The v values on bottom and top are v(j,i+1) and v(j+1,i+1)

If you use field.show(), it will also use that notation.
Does that solve your problem?

**Comment by schmidt-christina** [comment]
Hi Philippe,

I don't think this is a plotting problem as I use xarray.plot.pcolormesh() which centers pixels over their coordinates. So, exactly what we want on a T-grid.

I attached my notebook which I used to create the following figure:
![mismatch_between_oceantracer](https://user-images.githubusercontent.com/38216156/49809632-b5e1e180-fd5f-11e8-86eb-9898336a3a49.png)

I released the particles in the lower box in the gridbox marked by the asterix. Does that mean that if I want to release in a cell(i,j) with
tracer T(i,j) in the middle,
f(i,j) at the top right corner and
velocities u(i,j) at the right edge and
v(i,j) at the top edge,
ParticleSet.from_field() releases in cell(i+1,j+1)?

Furthermore, the interpolation of the ocean tracer is not correct and seems to be shifted by half a cell. See especially figure below, where it looks like it is shifted by half a cell up and right. Here, white cells are land and blue cells are ocean according to the tmask. Particles not influenced by land due to a linear interpolation should appear in yellow/white, particles influenced by land are black. So, we expect particles on land and within half a cell next to land to be black.


[tutorial_nemo_curvilinear_modified_bugsfixed.html.zip](https://github.com/OceanParcels/parcels/files/2668092/tutorial_nemo_curvilinear_modified_bugsfixed.html.zip)

**Comment by schmidt-christina** [comment]
Did you also look in ParticleSet.from_field() for a rectilinear A-Grid? I am working with data from CMEMS (see http://marine.copernicus.eu/services-portfolio/access-to-products/?option=com_csw&view=details&product_id=MEDSEA_ANALYSIS_FORECAST_PHY_006_013 for details) and found that I am not releasing in a gridbox, but shifted by half a gridbox in zonal and meridional direction.

**Comment by delandmeterp** [comment]
Hi Christina,

I haven't used `xarray.plot.pcolormesh()`, but it seems it simply wraps `matplotlib.pyplot.pcolormesh()`
http://xarray.pydata.org/en/stable/generated/xarray.plot.pcolormesh.html

If you go in pcolormesh docs, it says:

```
(X[i+1, j], Y[i+1, j])          (X[i+1, j+1], Y[i+1, j+1])
                      +--------+
                      | C[i,j] |
                      +--------+
    (X[i, j], Y[i, j])          (X[i, j+1], Y[i, j+1]),
```

But if you check NEMO data indexing (https://www.nemo-ocean.eu/doc/img360.png), you see that the color plotted should be C[i+1,j+1]
(watch out that there is the notation in NEMO use `j` where pyplot uses `i`)
We use NEMO indexing, so (one is not good or wrong, it is a choice), such that we have to take that into account when using pcolormesh.

**Comment by delandmeterp** [comment]
About the tracers:
If you use a tracer field in a C-grid, you assume that it is constant all over the cell, so you don't use 'linear' interpolation method.
This for example prevents that you have unrealistic values close to the land, but still in the sea.
If you want to use linear interpolation, you do not really use the c-grid format, but you can do it. But in this case, you should provide the lon, lat of the T nodes, not the F nodes, (so you basically use the tracer as a A grid).
In such as case, you will see problems close to the coast for example.

**Comment by delandmeterp** [comment]
If I remove this linear interpolation in master branch, everything goes as expected, no?

[example.html.zip](https://github.com/OceanParcels/parcels/files/2679538/example.html.zip)

**Comment by delandmeterp** [comment]
Finally, about A grid.

As I said, in a C-grid, you expect a tracer to be constant in a cell.
This means that we can use pcolormesh to plot it, and we can naturally release particles in a set (with pset.from_field) according to the density attached to this cell.

For a A-grid, the natural way to plot a field would rather be to use contourf, to see the bi-linear evolution of a field through a cell, but we do not do it (so far).
We simply plot the mean value of the 4 nodes around the cell.

We do the same for the from_field function. We release in this cell particles according to the mean* value in the cell.
Why mean* and not mean?
Because if one of the 4 corners of a cell is 0, it means that this cell is land, so we don't release particles at all in the cell. So we only release particles in cells if all cornes have a value (which defines a wet cell)

**Comment by erikvansebille** [comment]
Hi @schmidt-christina, we were wondering if this Issue is fixed for you now, or whether you still have problems. Also because this Issue is tightly linked to the release of v2.0 (see also https://www.geosci-model-dev-discuss.net/gmd-2018-339/), it would be good to confirm soon if this works or not

**Comment by schmidt-christina** [comment]
Hi @erikvansebille, I did not look into it further for curvilinear C-grids with the newer parcels version as I work now on a different project where we use model data on a A-Grid. On the A-Grid, this issue is fixed for me. However, I think it would help other users, if you would specify more clearly where particles are released when using pset.from_field. I assumed particles would be released within gridboxes where the coordinates indicate the centre of a gridbox, instead particles are released in an area between the centre of 4 gridboxes.
If I look into this issue on a C-grid within the next week, I will let you know.
