### ISSUE TITLE
Accessing Field data resulting in 'NoneType' object TypeError

### ISSUE THREAD

**Issue by michaeldenes** [OceanParcels/parcels#490]
Hello all,

I've found an issue when trying to access the data in a Field object (solved by running .show(), but that step shouldn't be necessary).
I create a fieldset as such:
`fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, indices)`
Then compute the gradient fields:
`(dUdx, dUdy) = fieldset.U.gradient()`
`(dVdx, dVdy) = fieldset.V.gradient()`
Then I try to access the data (for the first time value, and first depth value):
`dUdx0 = dUdx.data[0,0,:,:]`
Producing the following error:
`TypeError: 'NoneType' object is not subscriptable`

The interesting thing is if I run `fieldset.U.show()` prior to computing the gradients and accessing the data, everything works fine! I thought I would raise so that others won't run into the same problem.

Thanks, Michael

**Comment by erikvansebille** [comment]
Hi Michael,

You see this error because your field is in DeferredLoad mode, where nothing has been loading into the `fieldset.U.data` array yet, and hence the `dUdx.data` is also still `None`. Indeed, when you issue `.show`, the field gets loaded, and hence can be shown.

In #493, we no clarify the error. One solution is to use `fieldset.computeTimeChunk()`, or indeed to .`show()` the field. Hope this helps!
