### ISSUE TITLE
Field gradient calculator

### ISSUE THREAD

**Issue by Jacketless** [OceanPARCELS/parcels#60]
Getting the spatial gradient of a field with arbitrary lat/long spacings is none-trivial as the sample distance varies in the x direction by latitude.

I'm currently coding a static method that takes a field and calculates this gradient using central difference, and forward/backward difference at the edges and between NaN/real values. 

I suggest that each `Field` object has a `.gradient(time)` function, that calls this static method to return and equivalent gradient field that can then be stored as a new `Field` instance, if required. Any other ideas?

**Comment by erikvansebille** [comment]
This certainly is an interesting idea; it makes sense when the gradient needs to be calculated everywhere. But if the particles are only in a subregion of the domain, would it be overkill to calculate the gradient in the entire domain?

Anyway, perhaps this is the sort of optimisation that we can do in subsequent stages of development. Just like we can start optimising I/O then. 

So for now, feel free to create a `.gradient(time)` function indeed.

As for the edges between NaN and real values, how are you getting along with landmasks, @Abobie? Would it make sense to make a PR for just the landmasks, so that they can be used here in this function too?

**Comment by Jacketless** [comment]
Bounding boxes to limit the calculated gradient could be further arguments in addition to `time` that default to the whole grid?

I've left out dealing with landmasks for the moment, but I assumed at the edges I'll calculate just the forward or backward differences- as I do at the edges of the grid.

**Comment by erikvansebille** [comment]
Solved with #62
