### ISSUE TITLE
Problem in getting velocities: example tutorial_nemo_curvilinear

### ISSUE THREAD

**Issue by vincenzodetoma** [OceanParcels/parcels#638]
I have a problem in getting velocities from ORAS5 dataset (NEMO based ECMWF Reanalysis). It seems there's a stripe between the poles of the tripolar grid that is bad interpolated. Can you  help me to solve this issue? 

![image](https://user-images.githubusercontent.com/49952201/64437830-4c60ea80-d0c7-11e9-9928-b63826deaa7d.png)

I followed the example but even in that there's seems to appear the same issue, I attach the code used: 
from parcels import FieldSet, ParticleSet, JITParticle, ParticleFile, plotTrajectoriesFile
from parcels import AdvectionRK4
import numpy as np
from datetime import timedelta as delta
%matplotlib inline

data_path = 'NemoCurvilinear_data/'
filenames = {'U': {'lon': data_path + 'mesh_mask.nc4',
                   'lat': data_path + 'mesh_mask.nc4',
                   'data': data_path + 'U_purely_zonal-ORCA025_grid_U.nc4'},
             'V': {'lon': data_path + 'mesh_mask.nc4',
                   'lat': data_path + 'mesh_mask.nc4',
                   'data': data_path + 'V_purely_zonal-ORCA025_grid_V.nc4'}}
variables = {'U': 'U',
             'V': 'V'}
dimensions = {'lon': 'glamf', 'lat': 'gphif', 'time': 'time_counter'}
field_set = FieldSet.from_nemo(filenames, variables, dimensions, allow_time_extrapolation=True)

field_set.U.show(vmin=-0.5, vmax=0.5)

![image](https://user-images.githubusercontent.com/49952201/64438228-08bab080-d0c8-11e9-9f1c-6bc3a33e313f.png)

Hope You'll help me!! thanks for the attention :)

**Comment by erikvansebille** [comment]
Dear Vincenzo,

Your problem seems to be related to Earth periodicity combined with the fact that the 1st column  of NEMO data corresponds to 78°E. The script has either problems to reconnect mesh elements <78 and >78, or problems with the -180 +180 connection, or both.

However, I think this could be a plotting issue only, and a `pset.execute` may work fine. As I also just wrote on #637, the plotting routines in Parcels are _very_ rudimentary, and really should not be used for anything more than a quick check of the data. We early made the decision to focus on the particle computation, not plotting; with the limited resources we have, we can't do it both ;-)

My recommendation is just to write your own plotting routines, specific for your own experiment and tailored to whatever you need.
As a hint, you can write your plotting scripts based on what we do in https://github.com/OceanParcels/parcels/blob/master/parcels/plotting.py. This will help you to start your codes, and if you find what goes wrong with the parcels routine, you can also submit a PR

Good luck!
