### ISSUE TITLE
clang / compilation error?

### ISSUE THREAD

**Issue by mikaelk** [OceanParcels/parcels#649]
After pulling the latest master, and creating a new environment in anaconda using:
`conda env create --name py3_parcels2 --file environment_py3_osx.yml `

I cannot run my parcels scripts anymore, even the example_stommel.py file. The error which I get is as follows:

```
runfile('/Users/kaandorp/parcels/parcels/examples/example_stommel.py', wdir='/Users/kaandorp/parcels/parcels/examples')
Reloaded modules: parcels, parcels._version, parcels.fieldset, parcels.field, parcels.tools, parcels.tools.timer, parcels.tools.converters, parcels.tools.loggers, parcels.tools.error, parcels.tools.interpolation_utils, parcels.grid, parcels.gridset, parcels.particle, parcels.particleset, parcels.kernel, parcels.codegenerator, parcels.compiler, parcels.kernels, parcels.kernels.advection, parcels.kernels.diffusion, parcels.rng, parcels.particlefile, parcels.scripts, parcels.scripts.plottrajectoriesfile, parcels.plotting
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
/Users/kaandorp/anaconda3/envs/py3_parcels2/lib/python3.7/site-packages/xarray/core/dataarray.py:219: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  elif isinstance(data, pd.Panel):
Stommel: Advecting 1 particles for 600 days, 0:00:00
Traceback (most recent call last):

  File "<ipython-input-9-dd7246b51289>", line 1, in <module>
    runfile('/Users/kaandorp/parcels/parcels/examples/example_stommel.py', wdir='/Users/kaandorp/parcels/parcels/examples')

  File "/Users/kaandorp/anaconda3/envs/py3_parcels2/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Users/kaandorp/anaconda3/envs/py3_parcels2/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/kaandorp/parcels/parcels/examples/example_stommel.py", line 139, in <module>
    outfile=args.outfile, repeatdt=args.repeatdt)

  File "/Users/kaandorp/parcels/parcels/examples/example_stommel.py", line 90, in stommel_example
    moviedt=None, output_file=pset.ParticleFile(name=outfile, outputdt=outputdt))

  File "/Users/kaandorp/parcels/parcels/particleset.py", line 378, in execute
    self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs))

  File "/Users/kaandorp/parcels/parcels/kernel.py", line 194, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)

  File "/Users/kaandorp/parcels/parcels/compiler.py", line 66, in compile
    raise RuntimeError(err)

RuntimeError: Error during compilation:
Compilation command: mpicc -Wall -fPIC -I/Users/kaandorp/parcels/parcels/include -g -O3 -m64 -o /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.so /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.c -shared -m64
Source file: /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.c
Log file: /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.log

Log output: In file included from /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.c:1:
/Users/kaandorp/parcels/parcels/include/parcels.h:598:13: warning: incompatible pointer types initializing 'float (*)[ydim][xdim]' with an expression of type 'float (*)[zdim][ydim][xdim]' [-Wincompatible-pointer-types]
    float (*zvals)[ydim][xdim] = (float (*)[zdim][ydim][xdim]) grid->depth;
            ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: in '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.B.tbd', file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.B.tbd for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

When trying to create the environment on cartesius I get this error:
```
conda env create --name py3_parcels2 --file environment_py3_osx.yml 
Fetching package metadata .............

ResolvePackageNotFound: 
  - clang_osx-64

```

Am I doing something wrong?

**Comment by erikvansebille** [comment]
Sorry, because the mpi is not yet on anaconda, it's also not yet explained on the oceanparcels.org<http://oceanparcels.org> website.

But essentially the point is that you have to add the following commands:


export CONDA_BUILD_SYSROOT=/

export C_INCLUDE_PATH=$C_INCLUDE_PATH:/Applications/Xcode.app/Contents//Developer/Platforms/Mac


Does that work?

On Thu, 19 Sep 2019 at 14:59, Mikael Kaandorp <notifications@github.com<mailto:notifications@github.com>> wrote:

After pulling the latest master, and creating a new environment in anaconda using:
conda env create --name py3_parcels2 --file environment_py3_osx.yml

I cannot run my parcels scripts anymore, even the example_stommel.py file. The error which I get is as follows:

runfile('/Users/kaandorp/parcels/parcels/examples/example_stommel.py', wdir='/Users/kaandorp/parcels/parcels/examples')
Reloaded modules: parcels, parcels._version, parcels.fieldset, parcels.field, parcels.tools, parcels.tools.timer, parcels.tools.converters, parcels.tools.loggers, parcels.tools.error, parcels.tools.interpolation_utils, parcels.grid, parcels.gridset, parcels.particle, parcels.particleset, parcels.kernel, parcels.codegenerator, parcels.compiler, parcels.kernels, parcels.kernels.advection, parcels.kernels.diffusion, parcels.rng, parcels.particlefile, parcels.scripts, parcels.scripts.plottrajectoriesfile, parcels.plotting
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
INFO: Generating FieldSet output with basename: stommel
/Users/kaandorp/anaconda3/envs/py3_parcels2/lib/python3.7/site-packages/xarray/core/dataarray.py:219: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  elif isinstance(data, pd.Panel):
Stommel: Advecting 1 particles for 600 days, 0:00:00
Traceback (most recent call last):

  File "<ipython-input-9-dd7246b51289>", line 1, in <module>
    runfile('/Users/kaandorp/parcels/parcels/examples/example_stommel.py', wdir='/Users/kaandorp/parcels/parcels/examples')

  File "/Users/kaandorp/anaconda3/envs/py3_parcels2/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Users/kaandorp/anaconda3/envs/py3_parcels2/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/kaandorp/parcels/parcels/examples/example_stommel.py", line 139, in <module>
    outfile=args.outfile, repeatdt=args.repeatdt)

  File "/Users/kaandorp/parcels/parcels/examples/example_stommel.py", line 90, in stommel_example
    moviedt=None, output_file=pset.ParticleFile(name=outfile, outputdt=outputdt))

  File "/Users/kaandorp/parcels/parcels/particleset.py", line 378, in execute
    self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs))

  File "/Users/kaandorp/parcels/parcels/kernel.py", line 194, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)

  File "/Users/kaandorp/parcels/parcels/compiler.py", line 66, in compile
    raise RuntimeError(err)

RuntimeError: Error during compilation:
Compilation command: mpicc -Wall -fPIC -I/Users/kaandorp/parcels/parcels/include -g -O3 -m64 -o /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.so /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.c -shared -m64
Source file: /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.c
Log file: /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.log

Log output: In file included from /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/f08dfcf2e0e248cce8e6d50adf212164_0.c:1:
/Users/kaandorp/parcels/parcels/include/parcels.h:598:13: warning: incompatible pointer types initializing 'float (*)[ydim][xdim]' with an expression of type 'float (*)[zdim][ydim][xdim]' [-Wincompatible-pointer-types]
    float (*zvals)[ydim][xdim] = (float (*)[zdim][ydim][xdim]) grid->depth;
            ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: in '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.B.tbd', file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.B.tbd for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)


When trying to create the environment on cartesius I get this error:

conda env create --name py3_parcels2 --file environment_py3_osx.yml
Fetching package metadata .............

ResolvePackageNotFound:
  - clang_osx-64



Am I doing something wrong?

**Comment by mikaelk** [comment]
Not sure whether I did it correctly, but I am still getting errors
```
Stommel: Advecting 1 particles for 600 days, 0:00:00
Traceback (most recent call last):
  File "/Users/kaandorp/parcels/parcels/compiler.py", line 53, in compile
    subprocess.check_call(cc, stdout=logfile, stderr=logfile)
  File "/Users/kaandorp/anaconda3/envs/py3_parcels2/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpicc', '-Wall', '-fPIC', '-I/Users/kaandorp/parcels/parcels/include', '-g', '-O3', '-m64', '-o', '/var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/b8cbd04ca26cdf639378b00b9c4790d5_0.so', '/var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/b8cbd04ca26cdf639378b00b9c4790d5_0.c', '-shared', '-m64']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parcels/examples/example_stommel.py", line 139, in <module>
    outfile=args.outfile, repeatdt=args.repeatdt)
  File "parcels/examples/example_stommel.py", line 90, in stommel_example
    moviedt=None, output_file=pset.ParticleFile(name=outfile, outputdt=outputdt))
  File "/Users/kaandorp/parcels/parcels/particleset.py", line 378, in execute
    self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs))
  File "/Users/kaandorp/parcels/parcels/kernel.py", line 194, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)
  File "/Users/kaandorp/parcels/parcels/compiler.py", line 66, in compile
    raise RuntimeError(err)
RuntimeError: Error during compilation:
Compilation command: mpicc -Wall -fPIC -I/Users/kaandorp/parcels/parcels/include -g -O3 -m64 -o /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/b8cbd04ca26cdf639378b00b9c4790d5_0.so /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/b8cbd04ca26cdf639378b00b9c4790d5_0.c -shared -m64
Source file: /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/b8cbd04ca26cdf639378b00b9c4790d5_0.c
Log file: /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/b8cbd04ca26cdf639378b00b9c4790d5_0.log

Log output: In file included from /var/folders/52/ltrzxpv11pxbfmkbw9gs6xjc0000gq/T/parcels-503/b8cbd04ca26cdf639378b00b9c4790d5_0.c:1:
/Users/kaandorp/parcels/parcels/include/parcels.h:7:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.

Exception ignored in: <function ParticleFile.__del__ at 0x320ff3290>
Traceback (most recent call last):
  File "/Users/kaandorp/parcels/parcels/particlefile.py", line 193, in __del__
    self.close()
  File "/Users/kaandorp/parcels/parcels/particlefile.py", line 198, in close
    self.export()
  File "/Users/kaandorp/parcels/parcels/particlefile.py", line 345, in export
    raise RuntimeError("No npy files found in %s" % self.tempwritedir_base)
RuntimeError: No npy files found in out-RVKKMYJD

```
But maybe it's better if I leave this and use a previous version for now

**Comment by delandmeterp** [comment]
As Erik said, the first error you were facing was due to the need for this line:
export CONDA_BUILD_SYSROOT=/

The error that you have now should be fixed with the path the include directory. The exact one I put on my laptop is
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/Applications/Xcode.app/Contents//Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/
which is a bit different from what Erik proposed. Have a try with this one. But first check if that directory actually exists.

**Comment by mikaelk** [comment]
Thanks, this seems to work! If I try to do the same on cartesius, should I add a similar line to my .bash_profile ?

**Comment by delandmeterp** [comment]
Nop, Linux works smoothly :-)

**Comment by delandmeterp** [comment]
However, I remember that some of Parcels dependencies were not available on the old miniconda I was using. All you need now is to run `module load Anaconda3/5.0.1`
+ see surfsara recent mail (`module load 2019`? I haven't tried yet)

**Comment by mikaelk** [comment]
thanks, it's all working!
