### ISSUE TITLE
Issue on velocity process(?)

### ISSUE THREAD

**Issue by ryohekono** [OceanParcels/parcels#687]
## Issue
The visualizations have returned me strange value of water velocity.
Even though my hycom data has m/s units velocity, all of outputs respond like in m/hour scale.
Because of this, the travelling distance also gave me back ridiculously huge number of around 80000 km in 10 days travels.
Could anyone have a look at some results below?
I am not sure what part is causing this issue, or whether the hycom data itself is needed to be changed the units.

## Code and Results
`filenames = {'U': "hycom_glb_911_2016*uv3z.nc",
             'V': "hycom_glb_911_2016*uv3z.nc"}`
`variables = {'U': 'water_u', 'V': 'water_v'}`
`dimensions = {}`
`dimensions['U'] = {'lat': 'lat', 'lon': 'lon', 'depth': 'depth', 'time': 'time'}`
`dimensions['V'] = {'lat': 'lat', 'lon': 'lon', 'depth': 'depth', 'time': 'time'}`
`vmin = -2000`
`timestamps = np.expand_dims(np.array([np.datetime64('2016-01-%.2d' % m) for m in range(1, 11)]), axis=1)`
`fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, 
     timestamps=timestamps, allow_time_extrapolation=True)`

`pset = ParticleSet.from_line(fieldset=fieldset, pclass=JITParticle, size=5, start=(-130, 25), finish=(-140, 25), time=datetime(2016, 1, 1))`

`output_file = pset.ParticleFile(name="hycom_particles.nc",
                                outputdt=timedelta(hours=6))`
`pset.execute(AdvectionRK4,
             runtime=timedelta(days=10),
             dt=timedelta(minutes=5),
             output_file=output_file)`

`output_file.export()
plotTrajectoriesFile('hycom_particles.nc',
                     tracerfile='hycom_glb_911_2016010100_t000_uv3z.nc',
                     tracerlon='lon',
                     tracerlat='lat',
                     tracerfield='water_u');`
![hycom_figure](https://user-images.githubusercontent.com/56178123/68688733-3825e780-0567-11ea-8785-41d41ed49fea.png)

`pset.show(field=fieldset.U, vmin=-10.0, vmax=10.0, show_time=datetime(2016, 1, 1, 0))`
![hycom_figure3](https://user-images.githubusercontent.com/56178123/68698333-9effcc80-0578-11ea-9e0a-540cd941c3d0.png)

`pset.show(field=fieldset.V, vmin=-1500, vmax=1500, show_time=datetime(2016, 1, 1, 0))`
![hycom_figure2](https://user-images.githubusercontent.com/56178123/68698451-ca82b700-0578-11ea-8fda-c32620135a2e.png)

**Comment by erikvansebille** [comment]
It seems you haven't actually added the vmin to the creation of the FieldSet, so the high velocities are likely because of interpolation near land

**Comment by ryohekono** [comment]
@erikvansebille 
Dear Erik, thank you for giving it a look!
I've done with having 'vmin=-10.0' in a fieldset statement before, but it also didn't work and gave me the pretty much same result as you can see below.
`fieldset = FieldSet.from_netcdf(filenames,
                                variables,
                                dimensions,
                                timestamps=timestamps,
                                allow_time_extrapolation=True,
                                vmin=-10.0)`
This gives me back,
![hycom_figure4](https://user-images.githubusercontent.com/56178123/68774477-12f7ae80-0625-11ea-8f4d-658c1ccbd3af.png)


`pset.show(field=fieldset.U, vmin=-2.0, vmax=2.0, show_time=datetime(2016, 1, 10, 0))`
The result is,
![hycom_figure5](https://user-images.githubusercontent.com/56178123/68774653-53efc300-0625-11ea-80e5-68d84b3317e3.png)

I think this is irrelevant but I also gave it a try using "halo" statement for interpolation, but it also gave me the same results after running.

I'm sorry to take your time but could you possibly have a look again?
I want to visualize them in a right scale.

**Comment by jpollygda** [comment]
Utilizing [global HYCOM](https://www.hycom.org/data/glby0pt08/expt-93pt0) data, I am experiencing the same problems as described above. My apologies for exhuming this old thread but I hesitate to start a new issue and this discussion is highly related. Setting `vmin=-2000` in the generation of the `Fieldset` **does not fix the problem.**

For me this problem is unique to HYCOM; no such issues exist with NCOM data.

The velocity fields as interpreted by parcels (shown via `fieldset.U.show()`) are about 1000 times larger than in the netCDF file (shown via `xarray.dataset.water_u.plot()`). See the pictures below.

The velocity as shown in xarray (with default masking and scaling):
![image](https://user-images.githubusercontent.com/91630251/202806186-d43909d5-ee5b-48ee-b361-e3c5438f6461.png)

The velocity as shown in parcels has magnitudes ~1000 greater:
![image](https://user-images.githubusercontent.com/91630251/202806241-e988c801-3c37-42d9-afd8-2a6a5d6ab40c.png)

Note the HYCOM encoding information (per xarray) contains masking and scaling information:
```
{'zlib': False,
 'szip': False,
 'zstd': False,
 'bzip2': False,
 'blosc': False,
 'shuffle': False,
 'complevel': 0,
 'fletcher32': False,
 'contiguous': False,
 'chunksizes': (1, 1, 276, 226),
 'source': '/home/james.polly/repos/driftpredict/data/hycom_glby_930/hycom_glby_930_2022030212_t021_uv3z_clip.nc',
 'original_shape': (1, 1, 276, 226),
 'dtype': dtype('int16'),
 'missing_value': -30000,
 '_FillValue': -30000,
 'scale_factor': 0.001,
 'add_offset': 0.0}
```
If xarray loads the HYCOM data without the automatic masking and scaling, the data is loaded as shown in the image below:
![image](https://user-images.githubusercontent.com/91630251/202807398-fbd2e9f1-ed5d-449d-9797-267a218d7e22.png)

**Is there a scaling step that I am missing when create Fieldsets in parcels? This smells like a meters/kilometers conversion problem but I can't seem to pinpoint it.**

I have tried to set `vmin=-2000` and `vmin=-30000` in generating the `Fieldset` and this does not change fact that the parcels-interpreted velocity fields differ by a few orders of magnitude.

Any help is greatly appreciated!

**Comment by jpollygda** [comment]
I'll separately add that applying the following "improves" the parcels simulation using HYCOM in that the particle trajectories are much more believable. This is after fieldset generation but before `particleset.execute()`:
```
fieldset.U.set_scaling_factor(0.001)
fieldset.V.set_scaling_factor(0.001)
```
In doing this, a parcels simulation using HYCOM is similar to that of NCOM.

**How does one know that these scaling factors need to be applied?** I chose the 0.001 scaling factor due to it being listed in the NetCDF encoding information per xarray (see above post) as ` 'scale_factor': 0.001`.

I did not have to do this for NCOM simulations, which also have a `scale_factor` present in their NetCDF encoding data.

**Comment by erikvansebille** [comment]
Hi @jpollygda, thanks for your messages. Indeed, when you set `decode_times=False`, then _no_ decoding is applied, so also not on the velocities. Hence, you will indeed need to apply the conversion factor yourself. Your solution above is thus the right way to go:
```python
fieldset.U.set_scaling_factor(0.001)
fieldset.V.set_scaling_factor(0.001)
```

**Comment by jpollygda** [comment]
Hi @erikvansebille, I really appreciate your consideration and time in responding to my messages here!
