### ISSUE TITLE
questions or suggestions for the animated gif?

### ISSUE THREAD

**Issue by wongchieh** [OceanParcels/parcels#696]
hello,
  when I wanted to simulate the parcels using changing velocity,  I may draw like the example in the tutorial `Tutorial showing how to create Parcels in Agulhas animated gif`, but I have a problem that it can only execute one time each time. I mean that cause we didn't save the tragectory, so if we want to visualize the tragectory, we can't do it.   And my question is how to do that like what the function `plotTrajectoriesFile` do . if you haven't have a function for this, I have a proposal that you can expend the `parcels`  to changing  `velocity`, for its own showing trajectory function.

**Comment by erikvansebille** [comment]
Dear @wongchieh, thank you for your comment, and sorry for the slow reply. It were busy weeks..

I'm not sure I understand what you suggest and/or ask. If you want to visualise a trajectory, you _have_ to save it to a netcdf file, because Parcels only keeps the last position in its memory. Any visualisation and analysis  will therefore have to be done in post-processing
