### ISSUE TITLE
Recovery_map Key Error in kernel.py

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#712]
Some users have experienced an error with Recovery Maps, see #711 and then specifically https://github.com/OceanParcels/parcels/issues/711#issuecomment-573062528. See also https://github.com/OceanParcels/parcels/issues/711#issuecomment-573626786 for a response

**Comment by claudiofgcardoso** [comment]
Response to https://github.com/OceanParcels/parcels/issues/711#issuecomment-573626786:
Hi @ignasivalles, thanks for your feedback. Your error rises only when particles exit the domain? Mine rises when trying to delete the particle after it beaches in a custom kernel, following the same methodology as "Delandmeter, P., & van Sebille, E. (2019). The Parcels v2.0 Lagrangian framework: new field interpolation schemes. Geoscientific Model Development Discussions, (January), 1–24. https://doi.org/10.5194/gmd-2018-339" :
```python
def BeachTesting_2D(particle, fieldset, time):
    '''
    From Delandmeter, P., & van Sebille, E. (2019):
    At each time step, the particle position is first updated following NEMO 5 or CMEMS advection 
    is first run. Then the particle is checked to still be located in a wet cell, otherwise it 
    is pushed back to the sea using an artificial current. In a second step, the Stokes or 
    diffusion kernels are run. In this step, if the particle beaches, it stops moving.
    '''
    # beached : 0 at sea, 1 beached (stay there), 2 after non-beach dyn, 3 after beach dyn, 4 unbeach
    if particle.beached == 2 or particle.beached == 3:
        (U, V) = fieldset.UV[time, particle.depth, particle.lat, particle.lon]
        if math.fabs(U) < 1e-14 and math.fabs(V) < 1e-14:
            if particle.beached == 2:
                print("Particle [%d] beached at lon: %g and lat: %g (depth: %g). Doing the unbeaching" % 
                  (particle.id, particle.lon, particle.lat, particle.depth))
                particle.beached = 4
            else:
                particle.beached = 1
                print("Particle [%d] beached after stokes or windage interaction. Deleting (%g %g %g %g)" % 
                      (particle.id, particle.lon, particle.lat, particle.depth, particle.time))
                particle.delete()
        else:
            particle.beached = 0
```

**Comment by ignasivalles** [comment]
I'm not using this beaching kernel, it happens when they exit the domain

**Comment by erikvansebille** [comment]
I've been looking at your error today, @claudiofgcardoso; but I really can't find why this would be happing to you. My guess now is that when you delete particles in your `BeachTesting_2D()` kernel, these particles are somehow not 'properly' deleted by `Parcels.kernel` , causing the error. The problem is that because I don't have your flow fields, I can't replicate this behaviour (i.e. not properly deleting a particle), so I'm not sure how to effectively debug.

I'm now really speculating, but might the problem arise because you include the `BeachTesting` kernel multiple times? What if you include it only once in your concatenation of kernels?

**Comment by claudiofgcardoso** [comment]
Hi @erikvansebille, thank you for putting some time into this issue. I tried your suggestion of concatenate the `BeachTesting_2D` kernel only once after the concatenation of all the other kernels. The model runs only until the same error rises again, as the Kernel finds a particle on land and tries to delete. 

To see if this error persisted with other kernels that delete particles  I deliberately started some particles out of the domain and then added a simple kernel (below) to the `particle.execute(recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})`. The simulation ran normally without raising any error and managed to delete the particles. 

```python
def DeleteParticle(particle, fieldset, time):
    if particle.depth < np.float32(0.51):
        print('Particle moved outside depth domain (surface) -> %g m. Moving back to 0.51 m...' % particle.depth)
        particle.depth=0.51
    elif particle.depth > np.float32(100):
        print('Particle moved outside depth domain (deep layer)-> %g m. Moving back to 100 m...' % particle.depth)
        particle.depth=100
    else:
        print("Particle lost!! ID: %g and age: %g --> (lon: %g, lat: %g, Depth: %g, Time: %g)" % 
          (particle.id, particle.age, particle.lon, particle.lat, particle.depth, particle.time))
        particle.delete()
```

I also tried to remove the `particle.beached = 1` before the `BeachTesting_2D` deletes the particle, problem still persisted.. So I'm running out of options. The error seems to be linked with `BeachTesting_2D` but can't understand why..

**Comment by erikvansebille** [comment]
Thanks for digging deeper into this @claudiofgcardoso! 

So if I understand you correctly, then deleting one particle _before_ the `particle.delete()` in the `BeachTesting_2D` kernel is called fixes it? Does the deleting in the beaching kernel also work then?? 

That would be very strange... But also a hack around ;-)

**Comment by claudiofgcardoso** [comment]
I ran only with particles out of the domain, so all particles were deleted before the `BeachTesting_2D`... But that is a nice hack to check!

Update: 
Instead of concatenating `BeachTesting_2D()` kernel after all the other kernels (i.e. advection, stokes, windage, etc) I concatenated only once and right after the `AdvectionRK4()` and it worked without raising any error! Any ideas why?

**Comment by erikvansebille** [comment]
> Instead of concatenating BeachTesting_2D() kernel after all the other kernels (i.e. advection, stokes, windage, etc) I concatenated only once and right after the AdvectionRK4() and it worked without raising any error! Any ideas why?

No, I don't know why. So your code only works if the `BeachTesting_2D()` kernel comes second in the list of concatenations? What if you put it at the end? then you get the `recovery_map` error again??

**Comment by claudiofgcardoso** [comment]
Well, now I have it at 2nd and 8th position and it works.. But I did test it at the end of the list and the `recovery_map` error raised

**Comment by erikvansebille** [comment]
This is very strange. But glad that you now at least have a way to work around the `Recovery_map Key Error in kernel.py`

Let me know if you find any other relevant information that could lead to a hint why this Error occurs. BUt in the meantime I'm closing this Issue. OK?

**Comment by claudiofgcardoso** [comment]
Hi @erikvansebille. There are some updates regarding the recovery_map error. The reason why I didn't got any error yesterday, just by rearranging the `BeachTesting2D`, was because I forgot to remove one line in the `StokesDrag()` (`particle.beached = 3`) that made parcels skip `WindDrag()` kernel (only runs `if particle.beached == 0`). Adding `BeachTesting2D` after wind and stokes kernels resets the `particle.beached` to 0 if particle is not on land. 

So, error keeps rising. I tested several other hyphothesis and come to the following results:

- If I add only one of the `StokesDrag()` or `WindDrag()` to the kernels, the simulation runs without any error. Here's an examples of how parcels executes the kernels:

(printing everytime a kernel is executed)
Particle [427] advection
Particle [427] check beaching
Particle [427] stokes
Particle [427] difusion
Particle [427] check beaching
Particle [427] beached after stokes or windage interaction. Deleting (-15.5112 27.9883 0.51 864000)
Particle [428] advection
Particle [428] check beaching
Particle [428] stokes
Particle [428] difusion
Particle [428] check beaching

- Error only appears when both `StokesDrag()` and `WindDrag()` are added simultaneously:

Particle [148] advection
Particle [148] check beaching
Particle [148] stokes
Particle [148] wind
Particle [148] difusion
Particle [148] check beaching
Particle [148] beached after stokes or windage interaction. Deleting (-15.6117 28.0709 0.51 0)
Particle [149] advection
Particle [149] check beaching
Particle [149] stokes
Particle [149] wind
Particle [149] difusion
Particle [149] check beaching
(...)
What is curious here is that the error rises only at the end of the timeset. So, all particles are still executed within the same timestep and only at the end of it the error rises: 
(...)
Particle [285] advection
Particle [285] check beaching
Particle [285] stokes
Particle [285] wind
Particle [285] difusion
Particle [285] check beaching
Particle [286] advection
Particle [286] check beaching
Particle [286] stokes
Particle [286] wind
Particle [286] difusion
Particle [286] check beaching
Traceback (most recent call last):
  File "run_MAC_NEMO.py", line 108, in <module>
    track_kernels=args.track_kernels)
  File "run_MAC_NEMO.py", line 88, in p_advect
    chunksize=chunksize, track_kernels=track_kernels)
  File "/home/claudio/OceanParcels/MAC/MAC_NEMO.py", line 601, in MAC_NEMO
    execute_run(pset, kernel, start_date, finish_date, timestep, output_file, stop_release)
  File "/home/claudio/OceanParcels/MAC/MAC_NEMO.py", line 520, in execute_run
    recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})
  File "/home/claudio/miniconda3/lib/python3.7/site-packages/parcels/particleset.py", line 475, in execute
    self.kernel.execute(self, endtime=time, dt=dt, recovery=recovery, output_file=output_file)
  File "/home/claudio/miniconda3/lib/python3.7/site-packages/parcels/kernel.py", line 355, in execute
    recovery_kernel = recovery_map[p.state]
KeyError: 2

- If I remove the `particle.delete()` from the `Beach_Testing2D()`, I can run both `StokesDrag()` and `WindDrag()` simultaneously without any error. 

for info, `StokesDrag()` and `WindDrag()` are as follows:
```python
def WindageDrag(particle, fieldset, time):
    """
    Kernel for Euler Forward  computation of windage -> To use when windage is to 
    be computed following the current advection (to prevent no-beaching)
    """
    if particle.beached == 0 and particle.depth < 0.52: 
        if fieldset.track_kernels: print('Particle [%d] wind' %particle.id)
        (Uwnd, Vwnd) = fieldset.UV_wnd[time, 0, particle.lat, particle.lon]
        particle.lon += Uwnd * particle.dt
        particle.lat += Vwnd * particle.dt
        particle.beached = 3

def StokesDrag(particle, fieldset, time):
    """
    Kernel for Euler Forward  computation of Stokes -> To use when stokes is to 
    be computed following the current advection (to prevent no-beaching)
    """
    if particle.beached == 0 and particle.depth < 0.6: 
        if fieldset.track_kernels: print('Particle [%d] stokes' %particle.id)
        (Ustokes, Vstokes) = fieldset.UV_Stokes[time, 0, particle.lat, particle.lon]
        particle.lon += Ustokes * particle.dt
        particle.lat += Vstokes * particle.dt
        particle.beached = 3
```

**Comment by erikvansebille** [comment]
This really is very strange. Could you send me the C-file that is generated by Parcels? This is the file with the long file name that is shown after `INFO: Compiled ...`

Note that by default, this C-file is deleted at the end of a Parcels run. You can either copy it while parcels is running, or use the the new `delete_cfiles=False` argument on kernel creation that is introduced in https://github.com/OceanParcels/parcels/pull/715

**Comment by claudiofgcardoso** [comment]
Are you referring to "/tmp/parcels-1005/3f8ee99c8fb48a2dbcf7633cfe6670fa_0.so" ?
Where can I find this file? I already edited `kernel.py` and `particleset.py` to accomodate the new `delete_cfiles=False` argument, but cannot find the file..

**Comment by erikvansebille** [comment]
> Are you referring to "/tmp/parcels-1005/3f8ee99c8fb48a2dbcf7633cfe6670fa_0.so" ?
Yes, I'm keen to see the `/tmp/parcels-1005/3f8ee99c8fb48a2dbcf7633cfe6670fa_0.c` file, which should be there during the Parcels simulation

**Comment by claudiofgcardoso** [comment]
Sorry, was looking in the wrong dir. Here's the file
[9faa23d20711c49e0747e1d01f14fa6e_0.txt](https://github.com/OceanParcels/parcels/files/4086674/9faa23d20711c49e0747e1d01f14fa6e_0.txt)

**Comment by erikvansebille** [comment]
This seems a bindary file. I want the `.c` file (a C code file created by Parcels' codegenerator)

**Comment by claudiofgcardoso** [comment]
Sorry once again! Here the file:
[9faa23d20711c49e0747e1d01f14fa6e_0.txt](https://github.com/OceanParcels/parcels/files/4086699/9faa23d20711c49e0747e1d01f14fa6e_0.txt)

**Comment by erikvansebille** [comment]
Thanks for sending the code. This all looks in order; I really don't see why this bug would be happening..

Just to check; is this bug recovery_map Key error now holding you back or have you found a workaround?

**Comment by claudiofgcardoso** [comment]
Thank you for your feedback and for dedicating so much time into this issue.. The good news is that I found the reason behind the error! 

When looking at the outputs of a backward run (the only kind that worked, I don't know why) I verified that the output timestep wasn't consistent. The `outputdt` declared in `ParticleFile` was set to 5 days, but when `particle.beached` switched from 0 to 1 `particle.time` varied between 1 to 5 days. So, I switched the outputdt to 1 day and it runs without any error.

I think that the error may be related with the different timesteps being used in kernel execution and the writing of data into NetCDF. Nevertheless, I find it very strange that parcels is able to write data  when the run is set in backward time..

**Comment by claudiofgcardoso** [comment]
Simulation (forward in time) broke after 3h48m (68%) with error related with `recovery_map[p.state]`. Don't understand why now, since it managed to eliminate many particles before the error raised. So, it seems that the `outputdt=timedelta(days=1)` didn't solve the problem after all.

**Comment by ignasivalles** [comment]
hey @claudiofgcardoso just to know, are you releasing particles within a loop? I mean if you're using pset.execute in a while or for loop

**Comment by claudiofgcardoso** [comment]
Hi @ignasivalles. I use an "if" statement within a function for pset.execute. Here's the code:
```python
def execute_run(pset, kernel, start_date, finish_date, timestep, output_file, stop_release=None):
    dt=-timestep.total_seconds() if start_date > finish_date else timestep.total_seconds()
    if stop_release and (start_date >= stop_release >= finish_date or 
                         start_date <= stop_release <= finish_date):

        # running for the first years
        print('Running first part of simulation: from ' + 
              start_date.strftime("%Y/%m/%d") + " to " + stop_release.strftime("%Y/%m/%d"))
        pset.execute(kernel,                 # the kernel (which defines how particles move)
                     runtime=abs(start_date-stop_release),    # the total length of the run
                     dt=dt,      # the timestep of the kernel
                     output_file=output_file,  #the file name and the time step of the outputs
                     recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})         
        pset.repeatdt = None  # reset the particle release interval

        # executing the rest of the years
        print('Running second part of simulation: from ' + 
              stop_release.strftime("%Y/%m/%d") + " to " + finish_date.strftime("%Y/%m/%d"))
        pset.execute(kernel,
                     runtime=abs(finish_date-stop_release),
                     dt=dt,
                     output_file=output_file,
                     recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle})
    else:
        print('Running only one simulation: from ' + 
              start_date.strftime("%Y/%m/%d") + " to " + finish_date.strftime("%Y/%m/%d"))
        pset.execute(kernel,                 
                     runtime=abs(start_date-finish_date),
                     dt=dt,
                     output_file=output_file,
                     recovery={ErrorCode.ErrorOutOfBounds: DeleteParticle}) 
```
Do you think it may be related? In fact, everytime I do a test of 1 or 2 months (only one `pset.execute` with no interruption) it works, but I always thought it was related with the short time of execution.

**Comment by ignasivalles** [comment]
hey @claudiofgcardoso sorry for the late answer. The question was only to discard some source of errors because I was executing parcels within a while loop and adding and executing parcels with the same pset.file several times was a source of multiple errors... Now I changed my scripts and I'm executing parcels one time (I'm waiting if it works). In my case, the problem is that some of this errors (like that one) do not appear after some days of simulation, in short runs normally everything is fine, so debugging it takes time. I'm working also in a HPC (also another source of multiple errors ;) ).

**Comment by claudiofgcardoso** [comment]
No worries @ignasivalles, thank you for the feedback. It seems that the bug recovery_map Key error appears only with versions older than 2.0.0. Although it takes much more time with this old version (4 days instead of ~10 hours), the simulation succeeds. This test was carried on the laptop, so I'm not sure how it would behave on the HPC..
