### ISSUE TITLE
Velocity in spherical mesh

### ISSUE THREAD

**Issue by SaAlrabeei** [OceanParcels/parcels#809]
This is should not be posted as an issue, but I don't know where else to post. 
My current data is from the Copernicus platform, a global reanalysis product.  It is given in m/s unite. I saw the how parcels convert to m/degree. However, when I use the spherical mesh , the particles are advected too slowly. In reality, the particles ( Larvae or eggs which are passive swimmers) should be crossed at least two lon-lat degrees within 2-3 months. 

In the flat mesh, it looks more reasonable. 
The area of interest is not that polar. It is in the northern coast of Norway. 
Do I have to consider something else when using the spherical mehs? Do I have always to consider the spherical mesh? 

Best Regards
Salah

**Comment by erikvansebille** [comment]
Dear @SaAlrabeei. This depends on what the units are of your longitude and latitude. 

- If the units of longitude and latitude are in degrees, then you should use `mesh='spherical'` so that Parcels converts the velocities to degrees/m.
- If the units of longitude and latitude are in meters, then you should use `mesh='flat'` so that Parcels does not convert the velocities and keeps them in m/s

Hope this helps. Good luck!
