### ISSUE TITLE
Array shape error with parcels 2.1.5

### ISSUE THREAD

**Issue by pierrick-giffard** [OceanParcels/parcels#821]
I've an error with parcels 2.1.5 when I use tracers that haven't the same shape that current. I get the following error:

> Traceback (most recent call last):
>   File /data/rd_exchange2/pgiffard/stamm/src/STAMM.py, line 64, in <module>
>     pset = fc.create_particleset(fieldset, turtle, lon_init, lat_init, t_init, param)
>   File /data/rd_exchange2/pgiffard/stamm/src/Functions.py, line 141, in create_particleset
>     pset.execute(pk.CheckOnLand, dt=0)
>   File /data/rd_exchange2/pgiffard/anaconda/envs/lastparcels/lib/python3.6/site-packages/parcels/particleset.py, line 622, in execute
>     next_input = self.fieldset.computeTimeChunk(time, np.sign(dt))
>   File /data/rd_exchange2/pgiffard/anaconda/envs/lastparcels/lib/python3.6/site-packages/parcels/fieldset.py, line 896, in computeTimeChunk
>     data = f.computeTimeChunk(data, tind)
>   File /data/rd_exchange2/pgiffard/anaconda/envs/lastparcels/lib/python3.6/site-packages/parcels/field.py, line 1236, in computeTimeChunk
>     data = self.data_concatenate(data, buffer_data, tindex)
>   File /data/rd_exchange2/pgiffard/anaconda/envs/lastparcels/lib/python3.6/site-packages/parcels/field.py, line 1184, in data_concatenate
>     data = lib.concatenate([data_to_concat, data[tindex+1:, :]], axis=0)
>   File /data/rd_exchange2/pgiffard/anaconda/envs/lastparcels/lib/python3.6/site-packages/dask/array/core.py, line 3509, in concatenate
>     raise ValueError(Shapes do not align: %s, [x.shape for x in seq2])
> **ValueError: ('Shapes do not align: %s', [(1, 1, 2160, 4320), (2, 1, 2041, 4320)])**

The error is on a kernel executed only once but it also appears later if I switch this kernel off. I'm in 2D and 2041 and 2160 are the number of cells I have in the y direction for current and for my tracer, respectively.

**Comment by erikvansebille** [comment]
Can you give a bit more info on what your `Field` actually looks like? 

E.g. `print(FieldSet.__dict__)`, `print(Field.__dict__)` and `print(Field.grid.__dict__)` where `FieldSet` and `Field` are the names of your fieldset and the field that causes the ValueError

**Comment by erikvansebille** [comment]
Thanks for the info, this looks like a chucking error then. But I'm surprised you don't get an error that `chunksize='auto'` is not allowed when using different grids..
@CKehl, do you know why this is happening?

@pierrick-giffard, could you provide us with (a sample of) the data files so that we can have a look too?

**Comment by CKehl** [comment]
Hi @pierrick-giffard ,
Can you provide us not necessarily with the data but more importantly your parcels controlling script ? I would be important to see how you setup the fieldset. One thing appears a problem: in a multi-grid scenario (fields in a fieldset that do not all share the same grid), an auto-chunking (often) doesn't work. Reason for that: `dask` will decide then for each field a different chunking size, which conflicts with the indexing from the particle distribution, which determines which cells need to be loaded. It's something that will soon be added to the documentation. In short: when having a fieldset with multiple grids, you need to specify the chunking yourself. Please take inspiration for how to set it up from the file `example_dask_chunk_OCMs.py` in `<head parcels folder>/parcels/examples/`.

What is also suspicious is that it tries to concatenate a field that has a time dimension of 2 - should not happen cause the engine shall always load only 1 timestep (cause we explcitly buffer 3 timesteps). So, that is a bit curious with your error report.

Again, better help can be given if you could provide the parcels script you run.

Best,
Christian

**Comment by pierrick-giffard** [comment]
Hi,
Note that I didn't have any problem with parcels 2.1.4 (the problem might come from dask update ?). Here is my whole code, the fieldset definition is in `stamm/src/Functions.py --> create_fieldset`
[stamm.zip](https://github.com/OceanParcels/parcels/files/4528832/stamm.zip)

**Comment by CKehl** [comment]
Hi, I had a look on your script, and that the automatic setup worked out before was quite a lucky short, due to your multi-grid fieldset.

Now, one way to get around it: define the `field_chunksize=(<chunksize_time>, <chunksize_depth>, <chunksize_lat>, <chunksize_lon>)` or as a dictionary or dict of dicts. Again, please consult `example_dask_chunk_OCMs.py` for how to set it up.

Obviously, there is the issue that you need to somehow fix or know  the netcdf dimensions in advance. If you build some automated system (as it seems you do), you may wanna go an alternative root: create a fieldset with auto-chunking with UVT that share one and the same grid and one and the same size. create another, separate auto-chunking with NPP. Then, merge the two fieldsets by adding them up, create a summed or a vector field or something in that direction. That way, you can use the auto-chunking and still get around the issue.

Because of this issue, I may even forbid auto-chunking with multi-grid environments in future releases.

The other issue that chunking in 'auto' also attempts to chunk the time dimension, and that should not be done. That will be a bit of further thinking on our part.

**Comment by pierrick-giffard** [comment]
Hi,
I fixed it summing NPP to the fieldset containing U, V and T (letting chunking to auto), thanks for your solution. One more question: in my precedent message, we can see when I printed the U grid that it is written at the end `'cgrid': c_void_p(140178213667200)}`.  Does it mean it is considered U is defined on a C grid? Actually, my grid is an A grid.

**Comment by erikvansebille** [comment]
> One more question: in my precedent message, we can see when I printed the U grid that it is written at the end 'cgrid': c_void_p(140178213667200)}. Does it mean it is considered U is defined on a C grid? Actually, my grid is an A grid.

The `cgrid` and `c_void_p` here refers to the data structure in C (the programming language), not the Arakawa-C grid topology :wink:
