### ISSUE TITLE
RandomVonMises returns nan with high concentration parameters

### ISSUE THREAD

**Issue by pierrick-giffard** [OceanParcels/parcels#825]
I realized the function RandomVonMises sometimes returns nan with high values of concentration parameter (kappa), although the function itself hasn't problems with high kappas (I tested the C code). The weird thing is that it is capable of calculating the VonMises a few times but it fails after a certain point. I built below a very simple test in which after a few timesteps the VonMises returns nan.

[test_VonMises.txt](https://github.com/OceanParcels/parcels/files/4540651/test_VonMises.txt)

**Comment by erikvansebille** [comment]
Thank you for reporting this Issue, @pierrick-giffard. However, I can't run your code because I don't have the netcdf files. So I converted your code into the even simpler code below

```python
from parcels import random, FieldSet, ParticleSet, ScipyParticle

def VonMises(particle, fieldset, time):
    mean = 0.6  # mean angle
    kappa = 1e30  # concentration parameter
    tmp = random.vonmisesvariate(mean, kappa)/1000
    print(time, tmp)

fieldset = FieldSet.from_data({'U': 0, 'V': 0}, {'lon': 0, 'lat': 0})

pset = ParticleSet(fieldset, pclass=ScipyParticle, lon=0, lat=0)

pset.execute(VonMises, runtime=1000, dt=1)
```

If you run this code, you'll see that very occasionally, `tmp=nan`. On my system, it happens at `time=954`, but this may depend on your random seed. 

Now the question is: why does the `VonMises` function occasionally return nan. Since you've proposed this function @pierrick-giffard, could you have a look too?

**Comment by erikvansebille** [comment]
I've dug a bit deeper, and I think I know when the VonMises function returns an error (see also the [code here](https://github.com/OceanParcels/parcels/blob/master/parcels/include/random.h#L61-L108))

If on line 81, `u1=1`, then `z=-1` on line 82. If `r=1` because `kappa` is very large, then the denominator of `f` (`1.0 + q * z`) is `0.`, so that `f=nan`.

The question is now how to fix this. The problem is line 82, where  `u1=1` if `rand=RAND_MAX`.

**Comment by pierrick-giffard** [comment]
Good find! We might say if s = 0.5/kappa is close to zero, then directly return the mean angle mu?
