### ISSUE TITLE
 Issues with Parcels v2.2.0 installed with Python 3.8, on MacBooks running latest OS Catalina

### ISSUE THREAD

**Issue by JG-2020** [OceanParcels/parcels#849]
I encountered some issues with running the latest Parcels (2.2), installed with Python 3.8, on MacBooks running the latest OS Catalina (please see below). I have identified work-arounds for these issues, but am hoping that by posting here, we can get some advice about whether those workarounds are reasonable, and/or what else we should do and/or what they might need/want to change. I also had a question about implementing the Milstein in 2D with spatially-varying advection.

1) The newest Parcels does not appear to be backward compatible with previous versions because you cannot import the BrownianMotion2D or SpatiallyVaryingBrownianMotion2D built-in kernels. WORKAROUND: Use old version's kernel code as new version's custom kernel. Will this affect speed? If so, can they return old kernels back to Parcels so we can run old versions of our code? 

2) The new advection-diffusion kernels are only for 2D advection, and therefore new Parcels has lost the built-in functionality of simulating 3D advection with spatially-varying horizontal diffusion that you could do with old Parcels. WORKAROUND: I have modified the AdvectionRK4DiffusionM1 to do a 3D RK4 for advection, and am using this as a custom kernel inside the main code. Will this affect speed? If so, can they develop a 3D version (or add mine) to the built in kernels?

3) The new AdvectionRK4DiffusionM1 does not execute. I get:
AttributeError: 'FieldSet" object has no attribute 'dres'
Is there something else I need to import or define to make this work?
No workaround here: Right now using custom kernel with old SpatiallyVaryingBrownianMotion

4) Running with the newer versions of Parcels results in warnings that did not occur with older versions. Specifically, when loading files I get:
WARNING: Trying to initialize a shared grid with different chunking sizes - action prohibited. Replacing requested field_chunksize with grid's master chunksize.
WARNING: Field chunksize and Grid master chunksize are not equal - erroneous behaviour expected.
I am not sure what this warning means, and am a little concerned that our interpolation may be affected. Code still executes but want confirmation that this is not introducing a problem

5) Curious: I see that you have partitioned the calculation of the displacements due to advection and the displacements due to diffusion in AdvectionRK4DiffusionM1. These means that the estimate of spatially varying diffusion is not accounting for the contribution of advection to the distances over which diffusion would vary. I was wondering if you experimented with combining them, e.g. by including the Milstein kick into the "sampling" of rates of change at different locations that is done during RK4? 

Thank you.

**Comment by erikvansebille** [comment]
Dear @JG-2020. Thank you for reporting these five points. I will briefly respond to them below here:

1. Indeed, we chose not to keep backward compatibility of the old Brownian Motion Kernels, because we felt that their names were somewhat confusing. So we renamed the old `BrownianMotion2D` kernel to the new `DiffusionUniformKh`, but the functionality is the same.

2. Indeed, we have now only added 2D Kernels. 3D is more difficult, because ideally we would want to use isopcnal/diapycnal diffusivity, which requires rotating the diffusivity tensor. @daanreijnders is working on that. For now, I suggest you use your own 3D diffusivity kernel if you want; the whole idea of parcels is that anyone can write their own kernels!

3. For `AdvectionRK4DiffusionM1` to work, you need to add `dres` to the fieldset, using e.g. `fieldset.add_constant('dres', 0.00005)`. See also cell 4 of the [diffusivity tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_diffusion.ipynb).

4. These warnings can be ignored for now; @ckehl and I are working on them

5. I refer this question to @daanreijnders; perhaps he can answer?

**Comment by daanreijnders** [comment]
Adding to @erikvansebille’s answer:

1. Actually, the kernels are not the same. Previously, you would ‘chain’ advection and diffusion kernels, meaning you would first advect the particle, causing a displacement, and then diffuse the particle from this new location, causing a second displacement (or the steps interchanged). This is no problem when the diffusivity is uniform, but as soon as it varies spatially, your diffusion in one timestep is based on the diffusivity at the wrong location. The advection and diffusion vectors at each time step should be computed on the same location.
2. This is in the making, but it’s difficult since  indeed the whole diffusivity tensor is necessary to properly account for isopycnal diffusion when working in 3D. When creating your own kernel as a workaround, make sure to advect and diffuse in the kernel, i.e. save the particle’s location, compute the 3D advection and compute the 2D diffusion using this initial location and only add the displacement in the end. Chaining separate kernels leads to wrong results.
3. The resolution of the central difference to compute gradients in the diffusivity used to be set to a default value, but of course it depends on the grid resolution you use, so you have to make a decision about the size of this parameter yourself.
4.  /
5. Good point. This kernel is mathematically not sound, since the order the errors of advection (RK4) and that of diffusion (M1) are different. Higher order numerical schemes exist, but the issue is that since Parcels interpolates velocities, these higher order terms cannot be computed. I’m thinking about what would make the most sense to further improve the accuracy of the algorithms. You can still use this kernel though in case you cover regions where the diffusivity is negligible w.r.t. advection (i.e. the higher orders errors from RK4 dominate that from M1). Otherwise, use Milstein.

**Comment by daanreijnders** [comment]
And I forgot about your question related to speed: the extra computational step made by Milstein 1 w.r.t. Euler Maruyama is worth it for the improved accuracy. Differently put: M1 can achieve the same accuracy as E1 with a larger timestep and less computational cost.

**Comment by JG-2020** [comment]
Thanks for the help! I do have a couple of follow up comments though.

1. /

2. /

3. I had missed that fieldset.add_constant line in the tutorial. Thanks for pointing it out, and sorry for the bother. I had guessed that dres was the diffusivity resolution -- can you please confirm if the units of dres are in degrees?

4. /

5. I appreciate that the two methods (RK4 and M1) have different orders of accuracy, but I support you not worrying about using a higher order approach for horizontal diffusion. In my experience, the horizontal diffusivities in circulation model output are not precise. So it seems like overkill to spend effort on making the random kick calculations "accurate". I do agree that, if you are going to use Euler, you might as well use Milstein, because as you say, it is virtually no more work for much better accuracy. That said, if you ever want to explore higher order methods further, I did develop a RK version of a random kick, which appears to be more accurate than the Milstein especially when there are sharp gradients in diffusivity, as well as doing better near the boundaries. In my mind, this could be important if you ever develop vertical diffusion in Parcels. Vertical diffusivity gradients are arguably more realistic than horizontal ones and also have biological significance for our biological particle tracking. 

Thanks again.

**Comment by JG-2020** [comment]
We are happy to share the code but would like to do a last polish first. It might be a few days though, probably Wednesday at the earliest. Sorry for the delay, hopefully you don't mind waiting.

**Comment by daanreijnders** [comment]
Not at all. Thanks a lot!

On 8 Jun 2020, at 18:31, JaceG <notifications@github.com> wrote:

﻿

We are happy to share the code but would like to do a last polish first. It might be a few days though, probably Wednesday at the earliest. Sorry for the delay, hopefully you don't mind waiting.

**Comment by jwongala** [comment]
Hello. I currently have a similar issue getting the DiffusionUniformKh kernel to run. Here is the attempted code I used.

fieldset.add_field(Field("Kh_zonal", 10, lon=0, lat=0)) 
fieldset.add_field(Field("Kh_meridional", 10, lon=0, lat=0))

But when I execute parcels it gives me the below error message, while still providing an output file with particles being advected across the ocean.

INFO: Compiled RemoveParticleMortalityAdvectionRK4DiffusionUniformKh ==> /var/folders/23/3cyx87fx261ddp067s5wcxfc0000gn/T/parcels-501/8eaa6ba9944b502e99861f8b6c9daee1_0.so
WARNING: ParticleSet is empty on writing as array at time 3600

Any help provided would be greatly appreciated.

**Comment by daanreijnders** [comment]
Hi @jwongala, which version of Parcels are you currently using? There's been a change in the API as of Parcels 2.2.2: for constant diffusivities (implied in `DiffusionUniformKh`), you have to pass the diffusivities to the FieldSet as constants instead of fields, i.e. `fieldset.add_constant_field("Kh_zonal", VALUE, mesh="flat")`.

If you are not on Parcels 2.2.2, can you provide your full script?
