### ISSUE TITLE
Script runs in scipy mode instead of JIT

### ISSUE THREAD

**Issue by NiekK19** [OceanParcels/parcels#861]
Hi all,

I am trying to determine the volume transport of the particles in my script. For this I have added an extra variable to the particle class in order to store the initial value of the velocity field (since I don't think it is possible to use operators such as * in the initial value statement, I could live with only the velocity value and multiply with dx and dz during postprocessing).

```
class Properties(JITParticle):
     VT = Variable('VT', dtype=np.float32, initial=fieldset.V)
```

However, when I run the script, I get the following warning:

WARNING: Particle initialisation from field can be very slow as it is computed in scipy mode.

Actually I had this problem before, by adding the temperature, salinity and density fields. At that time, the problem was solved by taking the initial value as 0. For those it was not a problem, since I am interested in the values along the trajectories. But now with the volume transport, it is the opposite, I am interested in the initial value, and not in the values along the trajectories. 

Is the possibility of taking any other value than zero as initial value simply something that is not supported (yet)? Or am I overlooking something else?

**Comment by erikvansebille** [comment]
Hi @NiekK19; good that you're asking. This is something that I've wanted to create a tutorial for, for a long time...

In short:
1) Yes, you can use `initial=fieldset.V` in the way you did, and it does work. It just may take a long time for the ParticleSet to be created, depending on how big your FieldSet is
2) If all your particles start at the same time and you want to run in JIT mode anyways, then a _much_ quicker way to initialise the particles with a value from a Field is the following: 
    a. Initialise the variable with a value of 0.
    b. Create the ParticleSet
    c. Now define a Sampling Kernel
    ```python
    def SampleV(particle, fieldset, time): 
        particle.VT = fieldset.V[time, particle.depth, particle.lat, particle.lon]
    ```
    d. Now run the ParticleSet with only this Kernel for `dt=0`. 
    ```python
    pset.execute(SampleV, dt=0)
    ```
    This doesn't increase the time on the particles, but will assign the correct value for `particle.VT`. And it's fast because it's run in JIT mode
3) If your Particles start at a different time (e.g. because you use `repeatdt`), then things become a bit more complicated. I haven't tested it, but I can imagine that youo could do something like the following
    a) Initialise the variable with a value of 0 and also create another Variable `sampled` that you also initialise with 0
    b) Create the ParticleSet
    c) Now change the Sampling Kernel to something like
    ```python
    def SampleV(particle, fieldset, time): 
        if particle.sampled == 0:
             particle.VT = fieldset.V[time, particle.depth, particle.lat, particle.lon]
             particle.sampled = 1
    ```
    d) Now add this Kernel to the list of other kernels in your normal `pset.execute()`. Make sure it's the first Kernel, so that the sampling is done _before_ the particles are moved

By the way, you might want to also add `to_write='once'` to the `Variable` definition, so that it only gets written to the output file once. That reduces the size of the output file

Hope this helps!

**Comment by NiekK19** [comment]
Thanks @erikvansebille for your quick reply and advise! I will look into it.

**Comment by CKehl** [comment]
I think this trick would make a nice 'Example' for [parcels_contributions](https://github.com/OceanParcels/parcels_contributions)

**Comment by erikvansebille** [comment]
Hi @NiekK19. Not sure if you're still facing this problem, but FYI @reint-fischer wrote a new [Field sampling tutorial]( https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_sampling.ipynb) that details how to sample these fields
