### ISSUE TITLE
Almost same performance with MPI 

### ISSUE THREAD

**Issue by olmozavala** [OceanParcels/parcels#863]
Hello everybody, I have a global model that runs for 5 years with 32k particles. It has advection and diffusion and everything is looking great. But it takes around 9 days to finish all the 5 years so I moved the code to the cluster and run it with MPI.

After some very useful help from many of you on issue #810 I was able to make it work correctly.
The problem now is that I almost don't get any speedup, it seems the splitting of the regions is not being optimized through time. Some of the processors finish in less than 2 days while the last processor finishes after 7 days. 

The next screenshot shows that after 10 hours some processors have finished more than 55% of the timesteps, while others are just at 25%.  This behavior only gets worse through time. 

![Screenshot from 2020-06-15 12-47-35](https://user-images.githubusercontent.com/187196/84684361-8ee10e80-af06-11ea-8aab-50c983e96712.png)

Someone mentioned that kmeans is used to group the particles and split them by processor. Does kmeans gets executed only once or this splitting happens dynamically?
Or any idea of why this is happening?

Thanks again for your help.

**Comment by adele157** [comment]
Just a note to say that we've had similar balancing issues, so are very interested in a solution to this also. We're running with only a few thousand particles in a 3D Southern Ocean domain (0.1 deg resolution), and find that the execution time only scales well out to about 100 days, after which the particles are spread too far apart and too many memory chunks are being imported, which slows it down. Our solution at the moment is to do very short runs (50-100 days) and many loops.

**Comment by erikvansebille** [comment]
Thanks @olmozavala, for your question. Indeed, [we use `kmeans` for splitting the particles](https://github.com/OceanParcels/parcels/blob/master/parcels/particleset.py#L177-L196) by processor, but this is only done at the creation of the ParticleSet. After that, particles stay within their designated processor. The plan is to improve this with some sort of dynamic load balancing in a future version of Parcels, but that is not implemented yet

Your slowdown in `pset.execute()` is probably from the `dask` chunking, as @adele157 also suggested. Especially if you have a simulation where all your particles start close together but then spread out over time, Parcels will often need to load in new chunks. As this is presently done in SciPy mode, this can be very slow and a quite big overhead! The solution is to either run with `field_chunksize=False` in the FieldSet creation if it fits in memory, or to make your chunks a bit bigger so that you limit the number of times new chunks need to be loaded

Hope this helps! We're still developing the chunking features, hopefully over the next few months this will become more efficient

**Comment by olmozavala** [comment]
Thanks @adele157  and @erikvansebille . I'll test the suggested options (smaller time range and false field chunk). Even though I believe with `field_chunksize=False` the code crashed with out of memory error after 1 year or so.
