### ISSUE TITLE
Parcels experiments with high-resolution NEMO data

### ISSUE THREAD

**Issue by HandmannP** [OceanParcels/parcels#864]
Hey everybody,

I am currently setting up 4d experiments within high-res data from NEMO.
Somehow my experiments run into a Memory error or the workers are Killed.

I am seeding in a 2d area in the model and want to compute the trajectories 4 years as a
repetition of one year - say 2005. In the future experiments with no repetition and for longer periods are planned.
Is there a way to not read in all time steps with in the experiments but only what's needed?
obviously single files of the shape of (185, 46, 2499, 2404) are hard to maintain in memory.

So in the following there is a small example

**Comment by HandmannP** [comment]
[Example_4d_Nemo_trajectories_ph .txt](https://github.com/OceanParcels/parcels/files/4792090/Example_4d_Nemo_trajectories_ph.txt)

**Comment by erikvansebille** [comment]
Hi @HandmannP. From a quick look at your code, it seems that you use the default `deferred_load=True` already in your `FieldSet.from_nemo`, so Parcels should only have three time frames in memory at any moment. The size of your Fields in memory would thus be (3, 46, 2499, 2404), but remember you have at least 2 (U, V) and probably some more (W?, Temp?) of these, which is still quite large

In order to reduce memory load, you can use `dask` chunking, see https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/documentation_MPI.ipynb and http://oceanparcels.org/faq.html#performance, although that can in some cases slow down the simulation, see other discussions here in the Issue tracker. We are working on making this `dask` chunking faster.

**Comment by HandmannP** [comment]
Hi @erikvansebille,

I tried the solutions proposed above and I am still running into errors.
I set the field_chunksize='auto' and it starts to compute, then 
I get an error related to the field.py - please find the error message in the attachment.
Do you have an idea how to solve this?

**Comment by HandmannP** [comment]
[Experiments_model_spacial_original_daily_3d.txt](https://github.com/OceanParcels/parcels/files/4919351/Experiments_model_spacial_original_daily_3d.txt)

**Comment by erikvansebille** [comment]
Hi @HandmannP. I haven't seen this error before, I fear. It's indeed related to the field chunking, but I'm not sure what causes it. Are you running with the latest version of Parcels from git master? Or do you use the version from anaconda?

**Comment by HandmannP** [comment]
Hey Erik,

So The trick was to update my parcels version with the newest one through Conda (parcels 2.1.3 - parcels 2.2.0) and to load a smaller area than the whole model - for the experiments right now this is alright - though for longer integration It might be very helpful to be able to load the full model.
