### ISSUE TITLE
Issue with 3D advection near coastlines using b-grid data

### ISSUE THREAD

**Issue by stellema** [OceanParcels/parcels#876]
Hi, I'm using `from_b_grid_dataset` with OFAM3 data (fieldset created [like this](https://github.com/OceanParcels/parcels/issues/768#issuecomment-635702626)) and found that when some particles are near land, they are advected vertically, but not in the meridional or zonal direction. 

This may be caused by u-cell (u, v) and t-cell (w) differences in the "land" points of my OFAM3 data (z* config of MOM version 4p1d). For example, in the original netcdf file with 0.1 degree grid spacing there is a land point at (-0.85, 185.35) in the t-cell and four corresponding land points in the u-cell (-0.9, 185.3), (-0.8, 185.3), (-0.9, 185.4), (-0.8, 185.4) and then a particle will just sink/float (depending on w) when it gets near that land point at (-0.81, -185.4). 

An example trajectory slice from the particle file might look like this (dt =-60 minutes, outputdt =1 day):
```
<xarray.DataArray 'time' (obs: 5)>
array(['2012-09-07T12:00:00.000000000', '2012-09-06T12:00:00.000000000', '2012-09-05T12:00:00.000000000', '2012-09-04T12:00:00.000000000', '2012-09-03T12:00:00.000000000'], dtype='datetime64[ns]')
<xarray.DataArray 'z' (obs: 5)>
array([286.06945565, 292.02637346, 297.01698857, 310.18874864, 325.39149928])
<xarray.DataArray 'lat' (obs: 5)>
array([-0.87972778, -0.86687352, -0.83273101, -0.81432612, -0.81432612])
<xarray.DataArray 'lon' (obs: 5)>
array([185.46147945, 185.42964155, 185.40186039, 185.38885687, 185.38885687])
```

I don't think it has anything to do with the vertical coordinate given to `from_b_grid_dataset` as mentioned in [#860](https://github.com/OceanParcels/parcels/issues/860) since the problem occurs when using either `sw_ocean` or `st_ocean` (I generally use `sw_ocean`). I can create a workable example and send some sample data if needed.

Do you think I should use an anti-beaching type kernel, modify the interpolation method or possibly mask the t-cell variables with the u-cell land mask? I'd really appreciate any advice on how to proceed with this issue!

**Comment by adele157** [comment]
We’ve found for MOM5 data (as discussed in https://github.com/OceanParcels/parcels/issues/860), that we need to use st_edges_ocean for the vertical coordinate, as well as adding an additional surface layer to w. Is your top layer of sw_ocean and w defined at the surface or the bottom of the top z* layer?

**Comment by stellema** [comment]
Thanks @adele157, `sw_ocean` is similarily defined at the bottom of the z* layer. 
I'll check if that fixes the issue. 
Also, what do you think is the most efficient way to add the additional surface layer?

**Comment by adele157** [comment]
Options for adding another surface layer to w are:
1. If your data is small, you could resave the netcdf files.
2. Use the `FieldSet.from_xarray_dataset` method as suggested in https://github.com/OceanParcels/parcels/issues/860.
3. Change how the Parcels code [currently adapts](https://github.com/OceanParcels/parcels/blob/master/parcels/field.py#L2159-L2177) velocity data  for b-grid interpolation if the vertical dimensions of the velocity and the depth coordinate don't match.

@hrsdawson has tested using 2. that adding in the extra surface layer fixes the problem, and is working on 3. for a more long term solution. Note that we decided to copy the top layer of the w data for this additional layer rather than adding in a layer of zeros. We are planning to contribute an example using MOM5 output for future users once we have finalised the method.

I'd suggest linking up with @hrsdawson if you haven't already - I gather you're both at the CCRC?

**Comment by hrsdawson** [comment]
Hey @stellema thanks for raising this issue, we've had the exact same problem particularly along coastlines, and at depth near steep bathymetry such as continental slopes where the particles seem to get stuck at the edge of/in the tracer cell, outside the U and V velocity domain.

Providing st_edges_ocean (e.g. [0, 1.08, .... 5610, 5808]) certainly seems to help in that far fewer particles are getting stuck (I've tested this at depth on a continental slope but not near coastlines). However it doesn't completely fix the problem, and I am still getting a small number of particles stuck. The code below is how I set up parcels using the `from_xarray_dataset` method. This method assumes linear interpolation but you can set it to b-grid interpolation after the fact. In doing so, I assumed Parcels would want the U, V and W fields defined on the same points as per the `from_bgrid_dataset method`, which is what I've done below. I tested a run using this set up against a run using modified W netCDF files with the `from_bgrid_dataset method` and the trajectories appear to be the same, so (I think?) it's the right set up... Oh I should note, this method repeats the bottom layer of U and V rather than adding zeros to the bottom (need to add layer so the dimensions are the same) - I did this because for testing purposes where I'm looking the ocean isn't that deep so it didn't make a difference, but I should really change this to add zeros instead.

```
udata = xr.open_mfdataset(ufiles, combine='by_coords', chunks ={'time': 1, 'st_ocean': 7, 'yu_ocean': 300, 'xu_ocean': 400})
vdata = xr.open_mfdataset(vfiles, combine='by_coords', chunks ={'time': 1, 'st_ocean': 7, 'yu_ocean': 300, 'xu_ocean': 400})
wdata = xr.open_mfdataset(wfiles, combine='by_coords', chunks ={'time': 1, 'sw_ocean': 7, 'yt_ocean': 300, 'xt_ocean': 400})

# Repeat bottom layer of U and V
bottomu = udata.sel(st_ocean=slice(5700,5900))
udata = xr.concat([udata, bottomu], dim='st_ocean').chunk({'st_ocean': 7})
bottomv = vdata.sel(st_ocean=slice(5700,5900))
vdata = xr.concat([vdata, bottomv], dim='st_ocean').chunk({'st_ocean': 7})

# Repeat surface layer of W and reassign coordinates so they match for bgrid interpolation
surfacew = wdata.sel(sw_ocean=slice(0,1.5))
surfacew = surfacew.assign_coords(sw_ocean=(surfacew.sw_ocean*0))
wdata = xr.concat([surfacew, wdata], dim='sw_ocean').chunk({'sw_ocean': 7})
wdata = wdata.rename({'yt_ocean': 'yu_ocean', 'xt_ocean': 'xu_ocean'}).assign_coords(yu_ocean=(udata.yu_ocean), xu_ocean=(udata.xu_ocean))

# Reassign coordinates so they match for bgrid interpolation
udata = udata.rename({'st_ocean': 'sw_ocean'}).assign_coords(sw_ocean=(wdata.sw_ocean))
vdata = vdata.rename({'st_ocean': 'sw_ocean'}).assign_coords(sw_ocean=(wdata.sw_ocean))

# combine into one dataset
udata["wt"] = wdata.wt
udata["v"] = vdata.v


variables = {'U': 'u',
            'V': 'v',
             'W': 'wt'}
dimensions = {'U': {'lon': 'xu_ocean', 'lat': 'yu_ocean', 'depth': 'sw_ocean', 'time': 'time'},
              'V': {'lon': 'xu_ocean', 'lat': 'yu_ocean', 'depth': 'sw_ocean', 'time': 'time'},
              'W': {'lon': 'xu_ocean', 'lat': 'yu_ocean', 'depth': 'sw_ocean', 'time': 'time'}}

fieldset = FieldSet.from_xarray_dataset(udata, variables, dimensions, field_chunksize=(1,7,300,400)) 
fieldset.W.set_scaling_factor(-1)  # set scaling factor for vertical velocities to -1. 

# set interp method to bgrid
fieldset.W.interp_method = 'bgrid_w_velocity'
fieldset.U.interp_method = 'bgrid_velocity'
fieldset.V.interp_method = 'bgrid_velocity'

```

I'm interested to know if this helps with your particles near the coast? As Adele mentioned, I'm working on modifying the parcels code for bgrid velocity data from MOM but I'm still getting some particles stuck so I still think we'll need another solution on top, such as an unbeaching kernel or one of the other suggestions you had. I'm also interested to know what the best option might be?

**Comment by stellema** [comment]
Thanks @adele157 and @hrsdawson! I tried modifying the vertical coordinate and haven't had the same issues so far, but I would need to do more testing to give a solid answer to that. Since you are still getting particles stuck, I agree that we'll need another solution and the unbeaching kernel is probably the simplest to implement. 

I'm currently working an unbeaching kernel similar to [this](https://github.com/OceanParcels/Parcelsv2.0PaperNorthSeaScripts) using the [A-grid unbeaching velocities script](https://github.com/OceanParcels/Parcelsv2.0PaperNorthSeaScripts/blob/master/preprocess/unbeach_Afield.py) (possible typo on lines 33-34?).

Also, I found a potentially quicker (and hopefully correct) way to modify the `fieldset` vertical coordinate using `indices`! 
```
    variables = {'U': 'u', 'V': 'v', 'W': 'w'}
    dimensions = {'time': 'Time', 'depth': 'st_edges_ocean', 'lat': 'yu_ocean', 'lon': 'xu_ocean'}
    # u, v and w are the filename lists (u files contain the st_edges_ocean variable).
    files = {'U': {'depth': u[0], 'lat': u[0], 'lon': u[0], 'data': u},
             'V': {'depth': u[0], 'lat': u[0], 'lon': u[0], 'data': v},
             'W': {'depth': u[0], 'lat': u[0], 'lon': u[0], 'data': w}}

    # Repeat top level of W and last levels of U and V.
    n = 51  # len(st_ocean)
    indices = {'U': {'depth': np.append(np.arange(0, n, dtype=int), n-1).tolist()},
               'V': {'depth': np.append(np.arange(0, n, dtype=int), n-1).tolist()},
               'W': {'depth': np.append(0, np.arange(0, n, dtype=int)).tolist()}}

    fieldset = FieldSet.from_b_grid_dataset(files, variables, dimensions, indices=indices,
                                            field_chunksize=chunks, time_periodic=time_periodic,
                                            allow_time_extrapolation=time_ext)
```
I used `st_ocean_edges` instead of `sw_ocean_edges`, mostly because I found it's a more intuitive way to interpret the depth levels with the shift, but I'm not sure if its right. It also helps with an issue of this method - I'm not sure how to modify the top layer so that it is all zeros. Since 'st_edges_ocean' is greater than zero (2.5 m in OFAM3), if a particle gets too far into the top level it will throw an `ErrorCode.ErrorThroughSurface`, which can be mapped to a 2D advection `SubmergeParticle` kernel. Otherwise, we could put the last level of `W` at the top, since it is all zeros for me, but for some reason I couldn't get it to work for me.
