### ISSUE TITLE
minor installation issue

### ISSUE THREAD

**Issue by JamiePringle** [OceanParcels/parcels#901]
I was updating ocean parcels by doing a clean install in a new environment using the setup on the oceanparcels.org web site. When I went to run the test, it complained that the package "pytest" was missing. Installing it with the usual "conda install pytest" fixed the problem. 

Cheers,
Jamie

**Comment by erikvansebille** [comment]
Thanks for reporting, @JamiePringle! I've just created a PR at the conda-forge channel (https://github.com/conda-forge/parcels-feedstock/pull/60), but as @willirath [commented](https://github.com/conda-forge/parcels-feedstock/pull/60#issuecomment-669001788), it is not recommended to add dependencies that are not absolutely needed at runtime

I'd hesitate to add `pytest` in the list of packages on step 2 of http://oceanparcels.org/#installing, again, because most people won't need it. Do note that `pytest` is already listed in the [`environment_*.yml` files](https://github.com/OceanParcels/parcels/blob/master/environment_py3_linux.yml), so would be picked up under the 'Installation for developers' subheader.

Which test broke for you, @JamiePringle? Is it something that other users would also do?

**Comment by willirath** [comment]
Ah, it looks like there's some `import pytest` calls in the examples directory as well. The peninsula one that is recommended as a quick check in step 5 of the installation instructions also does this but doesn't seem to use pytests anywhere. Some of the examples use pytest as they also seem to be used in testing.

**Comment by erikvansebille** [comment]
> The peninsula one that is recommended as a quick check in step 5 of the installation instructions also does this but doesn't seem to use pytests anywhere.

That's because we also unit-test all our examples and tutorials, so we need `pytest` for that. 

@willirath, would you then recommend adding pytest to the conda-forge list after all (https://github.com/conda-forge/parcels-feedstock/pull/60)?

**Comment by willirath** [comment]
> @willirath, would you then recommend adding pytest to the conda-forge list after all (conda-forge/parcels-feedstock#60)?

No, I wouldn't do this. (Especially as currently Parcels is pinning pytest to a relatively old version.) Instead, the least intrusive solution might be adding a statement that for some of the examples, `pytest` needs to be installed with `conda install -n py3_parcels pytest`.

Long term, it might be good to split the examples into files that only contain things users are likely to need in production and integration tests maybe building on these. This could easily be done by `from example_peninsula import foo` in the integration test file.

**Comment by erikvansebille** [comment]
OK thanks @willirath. I've now added the installation instruction to oceanparcels.org
