### ISSUE TITLE
How to identify deleted particles?

### ISSUE THREAD

**Issue by ocgabs** [OceanParcels/parcels#918]
Hi, 
When using recovery={ErrorCode.Error: DeleteParticle} how can I identify deleted particles in the netCDF output? do they just stop being tracked?. Thanks in advance for your answer.

**Comment by reint-fischer** [comment]
Hi @ocgabs, 

The particles that are deleted can be identified in the output file because the values of the variables become `nan` (or `NaT` in the case of `time`) from the moment they get deleted.

If you want to be more explicit about when particles get deleted, you can also expand the DeleteParticle kernel. You can add a Variable to your particles that gets flagged in the DeleteParticle kernel or you can add a print statement so that you can see what particles get deleted e.g.:
`print('Particle '+str(particle.id)+' has been deleted at t = '+str(time)+' at lon, lat, depth = '+str(particle.lon)+', '+str(particle.lat)+', '+str(particle.depth))` 

I hope this answers your quesetion.
