### ISSUE TITLE
NestedField and SummedField

### ISSUE THREAD

**Issue by lucvandenbulcke** [OceanParcels/parcels#927]
Hello,
I'm trying to use at the same time 2 velocity sources (currents and Stokes drift) and grid nesting. I have 3 nested Nemo grids that I can use fine with Parcel 2.2 (following the Nemo and Nesting tutorials). I also can combine currents with Stokes drift obtained from CMEMS (so yet another grid), when I use just 1 of the 3 Nemo grids, e.g. following the SummedField tutorial, or alternatively using 2 kernels (as in the North Sea example).
The difficulties start when I want to use together grid nesting and currents+stokes drift. I tried the following:
* use summed fields and nestedfields in order to use just 1 kernel (advectionRK4). 2 variants are possible, 
** a Nestedfield of 3 summedfields, each one is the sum of the respective Nemo velocity and (always the same) Stokes drift velocity 
** a summedfield of a NestedField and the stokes drift. Neither solution seems to work. I suppose NestedField wants Fields, not SummedFields ; and the same the other way around.
* create a fieldset containing NestedField for U and V, then adding Stokes drift as a separate VectorField in the fieldset; Then I would use 2 kernels, advectionRK4  + StokesDrag (as in the North Sea examples).
** I cannot add the VectorField (Ustokes, Vstokes) directly to the fieldset containing the Nemo nestedfield, because it expects to find the fieldset.U.grid attribute, which does not exist (and indeed U is a NestedField instead of a regular Field)
** I added the Stokes drift Vectorfield to the fieldset1, the fieldset corresponding to one of the 3 Nemo fieldsets, then wrote something like
    `fieldset.UVs = fieldset1.UVs`    (where UVs is the VectorField containing the Stokes drift)
 Here, an error is raised when I try to add the StokesDrag kernel to the kernels variable, because the Field does not have the ccode_name attribute.
** If I first add both components of the Stokes drift velocity `fieldset_total.Us = fieldset1.Us` (and the same for V), then it accepts adding the StokesDrag kernel, but fails at the `pset.execute` line with the error that the RectilinearZGrid object does not have the update_status attribute.

Is there a preferred way to use both nesting and 2 velocity sources ? Or anything else that I forgot or did wrong ?

My source code is in the attached zip file ; the datafiles are large (~1GB) but I can share them somewhere on the web if it helps. 
Thank you !

[tracking.zip](https://github.com/OceanParcels/parcels/files/5294725/tracking.zip)

**Comment by erikvansebille** [comment]
Thanks @lucvandenbulcke, for reporting this bug. I think you're the first user who wants to use both NestedFields and SummedFields at the same time... We just haven't developed/tested this feature yet 

I can have a quick look if it's as easy as making sure that NestedFields also accepts SummedFields. 

If that turns out to be difficult to implement, then perhaps a solution is to put the SummedFields part explicitly in your kernels. So instead of a line like
```python
(u1, v1) = fieldset.UV[time, particle.depth, particle.lat, particle.lon]
```
use something like
```python
(u11, v11) = fieldset.UV[time, particle.depth, particle.lat, particle.lon]
(u12, v12) = fieldset.UVs[time, particle.depth, particle.lat, particle.lon]
u1 = u11 + u12
v1 = v11 + v12
```
which is what Parcels does under the hood anyways, for SummedFields. Note that this is different from defining a separate `StokesDrag_RK4` kernel and then appending to the normal `AdvectionRK4` as you did in your code, as in that case the particle will first be updated with UV and only after its location is updated will it 'feel' Stokes. That can lead to a different trajectory than computing `UV` and `UVs` _at the same times_

**Comment by lucvandenbulcke** [comment]
Thanks @erikvansebille for your answer.
I tried to apply your method. I create fieldset1, fieldset2, fieldset3 (each from Nemo), and then fieldset using NestedFields
Then I try to read in the Stokes drift. I cannot save the UVs VectorField to fieldset, because the "NestedField" has no attribute 'grid'
I then save UVs in fieldset1 , and just write fieldset.UVs=fieldset1.UVs (this works)

I wrote the Double_AdvectionRK4 kernel following your suggestion, but it fails with this error:
Traceback (most recent call last):
  File "forcoast.py", line 80, in <module>
    kernels = pset.Kernel(Dbl_AdvectionRK4_3D) if run3D else pset.Kernel(Dbl_AdvectionRK4)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/particleset.py", line 763, in Kernel
    delete_cfiles=delete_cfiles)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/kernel.py", line 148, in __init__
    self.funcvars)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/codegenerator.py", line 391, in generate
    self.visit(py_ast)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/codegenerator.py", line 422, in visit_FunctionDef
    self.visit(stmt)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/codegenerator.py", line 745, in visit_VectorFieldEvalNode
    self.visit(node.field)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/data/anaconda3/envs/py3_parcels/lib/python3.6/site-packages/parcels/codegenerator.py", line 720, in visit_VectorFieldNode
    self.vector_field_args[node.obj.ccode_name] = node.obj
AttributeError: 'VectorField' object has no attribute 'ccode_name'

Do you have an idea how I should set this attribute ?
Thank you very much !

**Comment by erikvansebille** [comment]
Hi Luc

I dug a bit into the code this afternoon, because I hoped it would be fairly simple to implement NestedSummedFields. But alas, it's not simple at all I fear.. It would require a major rewrite to do this, and I'm afraid we don't have the resources for that at the moment

As I said, the easiest work-around would be to treat your two fields that you want to sum as completely separate, and _only_ use the NestedFields functionality of Parcels. You'd then need to write a custom kernel for the summing of the fields, but that you can do with the hints I provided above

Good luck!
