### ISSUE TITLE
PARCELS v2.2.0, Developers Install on HPC w/ Intel C & Fortran compilers, particleset.ctypes_struct produces boolean

### ISSUE THREAD

**Issue by croachutas** [OceanParcels/parcels#928]
Due to the configuration of the HPC (CINES OCCIGEN, system details at https://www.cines.fr/en/supercomputing-2/faq-hpc/) I'm using (using Python 3.6.3, Intel C and Fortran compliers v17.2 and OpenMPI v2.0.4 built with intel compilers, all implemented as modules pre-built by the admins) I have been forced to install Parcel v2.2.0 following the 'Installation for developers' outlined on the main parcels website (yes, before you ask I did make sure all dependencies were present and up to date before running the install script), rather than via Conda (I can get Miniconda working on the HPC but I've been allocated a stupidly low limit on the number of files in my home directory...). 

When running any of the examples or my own code I got an error:

Traceback (most recent call last):
  File "example_nemo_curvilinear.py", line 127, in <module>
    run_nemo_curvilinear(args.mode, outfile)
  File "example_nemo_curvilinear.py", line 58, in run_nemo_curvilinear
    output_file=pfile)
  File "/home/croach/.local/lib/python3.6/site-packages/parcels/particleset.py", line 642, in execute
    execute_once=execute_once)
  File "/home/croach/.local/lib/python3.6/site-packages/parcels/kernel.py", line 399, in execute
    self.execute_jit(pset, endtime, dt)
  File "/home/croach/.local/lib/python3.6/site-packages/parcels/kernel.py", line 265, in execute_jit
    particle_data = byref(pset.ctypes_struct)
**TypeError: byref() argument must be a ctypes instance, not 'bool'**

When I added a few print() statements to my code or to example_nemo_curvilinear.py to examine what's happening with the particle set I found that printing out pset produces what you'd expected but printing out pset.ctypes_struct resulted in a boolean False.

I have previously installed Parcels v2.2.0 on my laptop (Windows, using Conda with Python 3.6.11 and GNU C & Fortran compilers) without issue and I have previously installed one of the early versions of Python v2 (unsure if v2.1 or 2.1.2) on OCCIGEN using the 'Installation for developers' (with Intel C and Fortran compilers and Python 3.6.3), again without issue.

EDIT: And just got Miniconda working on the HPC, and installed PARCELS 2.2.0 through it... It works fine, so the above error must be due to either the compilers or the details of the 'Installation for developers'.

**Comment by erikvansebille** [comment]
Thanks for reporting, @croachutas. I really have no idea what is going on here; we have not experienced this before. And we have limited expertise in installing on HPCs, so not sure we can be of much help
Perhaps trying to install under python3.8 could help? The latest `master` fully supports Python3.8

Good luck with trying to install Parcels on your system

**Comment by CKehl** [comment]
Looking at this issue, there must have been something going wrong with the installation of your Python (the `ctypes` version and functions are bound to the Python version). Also, it would be good to compare both environments (non-conda and conda) by printing out the `CC` environment variable. I assume that your miniconda does not use the Fortran C-compiler `icc` but `x86_64-conda_cos6-linux-gnu-cc`, which is Conda's cross-platform GCC derivative. As `ctypes` is dependent on the C compiler, this is a potential caveat or hazard in HPC setups.

I can understand that HPC maintainers are not overly happy about Conda solutions - it is a sub-optimal work-around, as it side-lines the computer-collective setup that has been installed and maintained for maximum efficiency and performance. Still and that-being-said, the Conda-version is the only means we officially support for running OceanParcels. It would otherwise not be attainable to enable OceanParcels across different hardware setups and operating system installations.

_Hoc concludere_: 

- It's nice you got the miniconda setup running. It's the go-to way to run OceanParcels - locally as well as on clusters. 
- Using the pre-defined/preset HPC environment (_without_ conda) is not something that can be done in general terms, and it would require in-depth installation and fine-tuning from your IT department to achieve this.
