### ISSUE TITLE
is there a way to pass var to kernel ?

### ISSUE THREAD

**Issue by quai20** [OceanParcels/parcels#956]
Hello, 
I want to have a function that generate my custom kernel. From what I understand I can't pass argument to the kernel function or use non-local var in it. Is there a way to do that ? I always end up with compilation issues.

For example, here, I tried to nest the `custom_kernel(particle, fieldset, time)` in a `create_kernel(var)`
```python
def create_kernel(var):
    custom_kernel(particle, fieldset, time):
        use of var...
return custom_kernel

```
The compilation of my kernel says that var is undefined.

If you have any ideas, I'm all ears,

thanks,

**Comment by reint-fischer** [comment]
Hi @quai20,
Thanks for opening the issue, this is something more people run into.
A good way to use global parameters in kernels is to use the method [`fieldset.add_constant()`](https://oceanparcels.org/gh-pages/html/#parcels.fieldset.FieldSet.add_constant). You can the access this constant in your kernel because you pass the fieldset as an argument. Is this what you are looking for? 

I'm not sure if there is a way to access a global variable that changes during your simulation. Then you might want to add the [`Variable`](https://oceanparcels.org/gh-pages/html/#parcels.particle.Variable) to your custom [`Particle`](https://oceanparcels.org/gh-pages/html/#module-parcels.particle) and update it in a separate kernel.

Cheers,

**Comment by quai20** [comment]
Hi @reint-fischer 
Thank you, `fieldset.add_constant()` did the trick. I didn't think to go with the fieldset since those var have nothing to do with the velocities but hey, that works :)
If I need to change those var during the simulation I will create another kernel for that, thanks for the advice.  
Cheers,
