### ISSUE TITLE
Parcels hangs when more than 10,000 temporary output files reached

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#961]
As found by @lourousselet, Parcels hangs when the number of `.npy` files in a temporary output directory reaches 10,000. This should be fixed

**Comment by erikvansebille** [comment]
Having explored this issue a bit more, it turns out that [the following lines](https://github.com/OceanParcels/parcels/blob/master/parcels/particlefile.py#L235-L236) to write the `pset_info.npy` file cause strongly nonlinear slowdown as the number of output files increases:
```python
with open(os.path.join(self.tempwritedir, 'pset_info.npy'), 'wb') as f:
    np.save(f, pset_info)
```

An example script that shows this nonlinear (exponential?) slowdown is
```python
xdim, ydim =40, 100
fieldset = FieldSet.from_data({'U': np.zeros((ydim, xdim), dtype=np.float32), 
                               'V': np.zeros((ydim, xdim), dtype=np.float32)}, 
                              {'lat': np.linspace(-60, 60, ydim, dtype=np.float32), 
                               'lon': np.linspace(0, 1, xdim, dtype=np.float32)})

pset = ParticleSet(fieldset, pclass=JITParticle, lon=0, lat=0)
pfile = pset.ParticleFile('pfile_largenumber.nc', outputdt=1)

def DoNothing(particle, fieldset, time):
    pass

pset.execute(DoNothing, runtime=1e5, output_file=pfile)
```
Not sure though how to fix this.

**Comment by CKehl** [comment]
The issue is with [those lines](https://github.com/OceanParcels/parcels/blob/master/parcels/particlefile.py#L229-L236), basically: among all the attributes `'time_written'` is exponentially increasing here, as it is written for every file (O(N)=N) and it is itself a constantly-expanding array with all written times of all particles for each file (O(N)=M) - hence, the drastic slowdown.

**Comment by CKehl** [comment]
So, from what we saw, there is no fix on this issue - it's just exponential complexity with the write-times. Best suggestion would be 'go easy on the output-dt', I presume ? As long as the snapshots in `pset_info.npy` store a history (which is required to do synchronization in a cluster-processing), this issue is going to remain.

**Comment by erikvansebille** [comment]
OK, then I'm closing this Issue for now..
