### ISSUE TITLE
Installation space

### ISSUE THREAD

**Issue by sophieschmiz** [OceanParcels/parcels#963]
Hi everyone, does anyone know the space needed for the local installation of the Parcels code?

**Comment by reint-fischer** [comment]
@erikvansebille, I talked with Sophie about this. My py3_parcels environment takes up about 3.3 GB. Should we keep track of this and maybe put in on the oceanparcels website?

**Comment by erikvansebille** [comment]
Yes, anaconda is not small unfortunately. Using [miniconda](https://docs.conda.io/en/latest/miniconda.html) instead might reduce the size of the whole package a bit?

Note that parcels code itself is mere megabytes and all the example data is ~400MB. So the rest of the environment is taken up by the dependencies

@willirath and/or @CKehl, can you weigh in on how/whether we can/should reduce the space requirements for conda/parcels?

**Comment by CKehl** [comment]
With Python and all the required sub-packages (i.e. dependencies) for numerical computation and notebook-interpretation (e.g. NumPy, SciPy, matplotlib, IronPython, Jupyter, etc.), 3.3 GB is actually quite small. My anaconda environment alone is 2.1 GB on Linux. If you run it all on Windows or Mac, the space requirement may be bigger because conda needs to pull and install packages that on Linux are part of the operating system by default.

I personally don't know about the different between Anaconda and Miniconda in installation size - nothing that really ever surfaced as a problem to me. Also, usually the space requirements for the fields of the simulation outweigh the conda space requirements by a substantial margin. I assume as long as the CI on github does not raise an error on space quotas for the installation, the installation size shouldn't be an issue to track continuously. That's just my personal opinion.
