### ISSUE TITLE
Performance with daily and hourly fields

### ISSUE THREAD

**Issue by julien-temple** [OceanParcels/parcels#983]
Hello,

I am new to Parcels and my team and I are facing a problem of performance: 
Usually, we perform simulations with daily forcing files (CMEMS PSY4, surface extracted) with 5000 particles. When using hourly forcing files, we expected the execution to be 24 times more slowly than simulations with daily forcing files. However, it is not the case as you can see in the following figures from a small test :

<img src="https://user-images.githubusercontent.com/77678782/105046281-31e3a300-5a69-11eb-906a-8c53ec4fa05f.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/77678782/105046301-390ab100-5a69-11eb-8c43-fa24af00dce6.png" width=50% height=50%>

You can see than the time ratio `hourly/daily` is around 24 for short simulations but is then increasing linearly with simulation time. In this study we let chunksize to default. 

Is there an explanation for this behaviour ?
Thanks for your help .

Julien.

**Comment by erikvansebille** [comment]
Thank you @julien-temple, for reporting this! This indeed does not look very good. Can I ask which version of parcels you are using? The latest on conda? Or the latest master branch from github? 

Because we have recently implemented two changes (#976 and #978) that potentially speed up Parcels significantly, especially if you use dask chunking and/or if your input files are very large so that they don't fit into memory well (and consequently trigger swap-memory).

**Comment by julien-temple** [comment]
Thank you for your response. We are using parcels 2.2.0 on conda.

**Comment by erikvansebille** [comment]
OK thanks; would you mind trying with the latest version of parcels from the github `master` branch?

**Comment by julien-temple** [comment]
Sure, I just installed it. I am performing the same test to see if there is a different behaviour. Thank you again.

**Comment by julien-temple** [comment]
Indeed, the execution is now really faster. We can see it with the following figures. The ratio `hourly/daily` is around 24 and does not increase as it used to :

<img src="https://user-images.githubusercontent.com/77678782/105188860-a0416780-5b34-11eb-8746-8c49fc08ce19.png" width=50% height=50%>

<img src="https://user-images.githubusercontent.com/77678782/105188867-a1729480-5b34-11eb-85bb-f64716dea368.png" width=50% height=50%>

Thank you very much !

**Comment by erikvansebille** [comment]
That is very good to hear; I'm really glad about this! Pinging @CKehl and @reint-fischer, so that they are aware too that the latest `master` (237d85b) has much better performance

By the way, it's hard to see from the graphs but is the 'Daily forcing files' run also faster; or is it roughly the same speed as before?

**Comment by julien-temple** [comment]
For daily fields, the execution time is almost the same for both parcels versions. The following figure plot execution time (with daily fields, 20 particles) for both 2.2.0 version and last version from `master` branch :


<img src="https://user-images.githubusercontent.com/77678782/105193446-cd901480-5b38-11eb-98d0-3d43384df374.png" width=50% height=50%>
